- contracts/validator/contract/ValidatorKyc.sol
> Made kyc mapping publc.

- rpc/server.go
Enable SendTransaction over RPC .
> Enable SendTransaction over RPC .

- contracts/validator/contract/ValidatorKyc.sol
Development comment added in smart-contract.
> Development comment added in smart-contract.

- contracts/validator/contract/ValidatorKyc.sol
Fixed a bug in propose & voteInvalidKYC
> fixed minor issues, typos

- contracts/validator/contract/ValidatorKyc.sol
removed old chain child-parent concept
> updated modifier isKYCWhitelisted

- contracts/validator/contract/validatorKycHotfix.sol
Contract with the same functionality as the validatorKyc.sol contract and with exact same constructor inorder to fix binding issue.
> constructor binding : hotfix

- contracts/validator/contract/XDCValidator.sol
Send either a candidate / owner & it will look up the KYC hash accordingly
> added : generalised  getKYC()

- common/constants.go
Maximum number of Masternodes Set to 21
> Maximum number of Masternodes Set to 21

- common/constants.go
RewardMasterPercent = 40
RewardVoterPercent = 30
RewardFoundationPercent = 30
> Change in Rewards | Rewards Ratio change

- contracts/validator/contract/XDCValidator.sol
Now the funds will get refunded if the parameters are not proper.
> fixed : issue in KYCWhitelisted

- contracts/validator/contract/XDCValidatorTest.sol
This contract has a provision to upload a KYC multiple times over.
New funs : getHashCount, getLatestHash
> added: validator with multiple uploadKYC

- contracts/validator/contract/XDCValidator.sol
made voteInvalidKYC slightly less costlier in terms of gas costs.
> updated voteInvalidKYC

- contracts/validator/validator.go
> Params Updated

- consensus/XDPoS/XDPoS.go
- core/blockchain.go
I have updated shuffle algorithm to resolve some problem
> update XDPoS shuffle Masternodes

- accounts/abi/bind/backends/simulated.go
- accounts/abi/bind/bind_test.go
- accounts/abi/bind/util_test.go
- cmd/puppeth/wizard_genesis.go
- common/types.go
- consensus/XDPoS/XDPoS.go
- contracts/blocksigner/blocksigner_test.go
- contracts/chequebook/cheque_test.go
- contracts/ens/ens_test.go
- contracts/randomize/randomize_test.go
- contracts/utils_test.go
- contracts/validator/validator_test.go
- core/blockchain.go
- eth/api_backend.go
- internal/ethapi/backend.go
- les/api_backend.go
- miner/worker.go
- params/config.go
- tests/block_signer_test.go
- tests/end_to_end/block_signer_test.go
This PR contain the bug fix for Xinfin forking issue with extensive test coverage.
> Forking incident fix

- consensus/XDPoS/engines/engine_v2/forensics.go
- consensus/XDPoS/engines/engine_v2/vote.go
- consensus/XDPoS/utils/pool.go
- consensus/tests/engine_v2_tests/forensics_test.go
- consensus/tests/engine_v2_tests/vote_test.go
- core/types/forensics.go
* add vote same round detection
add test for vote same round detect
finish process equivocate (not finish report)
* finish vote equivocation report, refactor code (vote -> forensics)
* finish process equivocate and report, and test
> Xin-200 Vote Equivocation (#111)

- cicd/devnet/start.sh
- Support custom verbosity configuration via env variable for the devnet docker image
> Allow custom verbosity

- cicd/devnet/terraform/efs.tf
- cicd/devnet/terraform/main.tf
- cicd/devnet/terraform/variables.tf
- Provision EFS, Security groups, IAM and other resources on devnet via terraform.
> Xin 293 add more terraform managed resources

- cicd/devnet/terraform/.terraform.lock.hcl
- cicd/devnet/terraform/container-definition.tpl
- cicd/devnet/terraform/ecs.tf
- cicd/devnet/terraform/efs.tf
- cicd/devnet/terraform/main.tf
- cicd/devnet/terraform/variables.tf
- Add task definition for running ECS
> XIN-242: Define task definition for running ecs cluster

- .travis.yml
Remove the unused travis stages.
> remove unused travis stage

- cicd/devnet/terraform/ecs.tf
> upgrade fargate spec to test if node crash or not

- eth/api_tracer.go
cherry-picked from https://github.com/ethereum/go-ethereum/commit/106d196ec4a6451efedc60ab15957f231fa85639
> fix-CVE-2018-16733

- core/vm/contracts.go
cherry-pick from https://github.com/ethereum/go-ethereum/commit/d8ada03eacbb54c18105f6c3f6f6d6ff4536f5b0
> fix-CVE-2020-26241

- cmd/puppeth/wizard.go
- cmd/puppeth/wizard_genesis.go
Also remove genesis tile in the output file as the real genesis file doesn't include that either
> add v2 config into genesis wizard

- cmd/puppeth/wizard_genesis.go
- consensus/XDPoS/XDPoS.go
- consensus/XDPoS/engines/engine_v1/engine.go
- consensus/XDPoS/engines/engine_v2/engine.go
- consensus/tests/engine_v2_tests/initial_test.go
- miner/worker.go
- params/config.go
Waitperiod have similar functionality with MinePeriod, so we merge it and avoid more explanation on how they difference
> merge waitPeriod into minePeriod

- common/constants/constants.go.devnet
This is missing from this PR: https://github.com/XinFinOrg/XDPoSChain/pull/194
> add parameter into devnet config

- .github/pull_request_template.md
- .gitignore
The template only take affect after merging into the default branch (master)
> Add pull request template

- .github/pull_request_template.md
- .gitignore
> Dev upgrade resolve conflict

- params/version.go
This is for version bump for current master
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
> bump current master version to 1.4.8

- params/version.go
Resolve Dev-upgrade to Master conflict
> Dev upgrade resolve conflict 2

- cicd/devnet/terraform/module/region/ecs.tf
> bump memory for fix

- .github/pull_request_template.md
> Make-pull-request-template-shorter

- common/constants/constants.go.testnet
Use the right apothem config for testnet
> update apothem config

- consensus/XDPoS/XDPoS.go
- consensus/XDPoS/engines/engine_v2/utils.go
- internal/ethapi/api.go
Add Signer API function in consensus v2
> Bug Fix: V2 getSigner API

- .github/pull_request_template.md
Resolve conflict from master to dev-upgrade
> Resolve master conflict

- cicd/devnet/start.sh
- cicd/mainnet/start.sh
- cicd/testnet/start.sh
Fix script for syncing issue
Regarding this issue https://github.com/XinFinOrg/XDPoSChain/issues/268#issuecomment-1577045170
> fix cicd script

- cicd/devnet/start.sh
- cicd/mainnet/start.sh
- cicd/testnet/start.sh
> fix cicd script (#318)

- common/constants/constants.go.testnet
- params/config.go
- params/version.go
Start set v2 block on testnet, target next week to perform switch
> set testnet v2 block

- common/constants/constants.go.testnet
* Merge 1 commit
current testnet masternode in smart contract is 15 on testnet from https://github.com/XinFinOrg/XDPoSChain/pull/333
> current testnet masternode is 15 (#333)

- accounts/abi/bind/base.go
- cmd/XDC/config.go
- common/constants.go
- common/constants/constants.go.devnet
- common/gas.go
- contracts/trc21issuer/simulation/test/main.go
- contracts/trc21issuer/trc21issuer_test.go
- core/chain_makers.go
- core/state_processor.go
- core/tx_list.go
- core/tx_pool.go
- core/types/transaction.go
- eth/api_tracer.go
- eth/gasprice/gasprice.go
- internal/ethapi/api.go
- les/odr_test.go
- light/odr_test.go
- miner/worker.go
- tests/state_test_util.go
This PR closes issue #288, change gas price from 250000000 to 12500000000. The new gas price will take effect from block number:
- devnet: 9757200, Fri Aug 25 2023 11:00:00 GMT+1200
- testnet(apothem): TIPTRC21Fee + 30000000 = 23779191 + 30000000 = 53779191
- mainnet(xinfin): TIPTRC21Fee + 30000000 = 38383838 + 30000000 = 68383838
- [✅] New feature
- [✅] Network
Run below tests before and after the time of taking effect.
Call the method `eth_gasPrice`, check the response:
```bash
curl -s -X POST -H "Content-Type: application/json" …
```
> Increase gas price from 250000000 to 12500000000

- common/sort/slice.go
- consensus/XDPoS/utils/utils.go
- core/blockchain.go
- eth/hooks/engine_v1_hooks.go
- internal/ethapi/api.go
Support golang v1.21 by import the codes of function `sort.Slice` from standard library v1.18.
- [✅] Not sure (Please specify below)
> Support golang v1.21

- p2p/peer.go
cherry-picked from https://github.com/ethereum/go-ethereum/pull/27887
- [✅ ] Bugfix (non-breaking change which fixes an issue)
- [✅ ] Network
- [✅ ] Geth
- [✅ ] This PR has sufficient test coverage (unit/integration test) OR I have provided reason in the PR description for not having test coverage
> fix-CVE-2023-40591

- common/constants/constants.go.testnet
setup new testnet block for enough buffer
> add testnet block for v2

- .travis.yml
- eth/downloader/downloader_test.go
Add deploy notification on devnet
> add notification script

- .travis.yml
> fix notification syntax

- .travis.yml
> use TRAVIS_COMMIT

- common/constants.go
- common/constants/constants.go.testnet
Define gas switch number for testnet to test, same as v2 switch number
> define gas switch block number for testnet

- cicd/devnet/terraform/module/region/container-definition.tpl
- cicd/devnet/terraform/module/region/ecs.tf
Continue from the previous PR to allow devnet CICD to auto-deploy multiple versions of the XDC nodes for the backwards compatibility tests.
> add support for custom docker image namespace

- consensus/XDPoS/engines/engine_v1/engine.go
- consensus/XDPoS/engines/engine_v2/vote.go
- eth/handler.go
Improve log level to make user friendly and log more sensitive.
> Improve log

- XDCx/XDCx.go
- common/constants.go
- common/constants/constants.go.devnet
- common/constants/constants.go.testnet
- consensus/XDPoS/engines/engine_v2/engine.go
- consensus/XDPoS/engines/engine_v2/mining.go
- consensus/XDPoS/engines/engine_v2/timeout.go
- consensus/XDPoS/engines/engine_v2/vote.go
- consensus/tests/engine_v1_tests/block_signer_test.go
- consensus/tests/engine_v2_tests/authorised_masternode_test.go
- consensus/tests/engine_v2_tests/mine_test.go
- consensus/tests/engine_v2_tests/verify_header_test.go
- internal/ethapi/api.go
- params/config.go
- params/config_test.go
Since we used to put max masternode constant number in constant file, it's time to move away constant into config specific for V2 for dynamic update max masternode on different environment
> Move masternode in v2 config

- consensus/XDPoS/engines/engine_v2/engine.go
- consensus/XDPoS/engines/engine_v2/mining.go
- consensus/XDPoS/engines/engine_v2/verifyHeader.go
- consensus/tests/engine_v2_tests/verify_header_test.go
- eth/downloader/queue.go
- eth/hooks/engine_v2_hooks.go
- params/version.go
Resolve sync issue by passing right round number
> resolve sync issue by passing right round number

- consensus/XDPoS/engines/engine_v2/vote.go
Change log level for normal network delay case
> change vote log level

- XDCx/XDCx.go
- XDCxlending/XDCxlending.go
Remove the unnecessary `_` assignment. 
> fix: remove unnecessary assignment

- core/types/order_transaction.go
> remove key with empty value from map txs in function NewOrderTransactionByNonce

- XDCxDAO/leveldb.go
- XDCxDAO/mongodb.go
Fix issue with of the unused methods that has infinite recursive implementations.
Trading and lending
> Fix xdcx infinite recursive calls

- XDCx/XDCx.go
- XDCx/tradingstate/relayer_state.go
- core/types/lending_transaction.go
- core/types/order_transaction.go
- core/vm/privacy/bulletproof.go
Improve the return statement efficiency
> chore: return statement optimization

- core/vm/privacy/ringct.go
Remove the unused method inside the ringct.go
> chore: remove the unused method in ringct.go

- cmd/swarm/hash.go
Fix Potential Index Out of Bound in swarm hash.go
> fix: Fix Potential Index Out of Bound

- XDCxDAO/leveldb.go
- XDCxDAO/mongodb.go
Remove the redundant nil check in trading and lending if statement
> chore: remove redunant nil check

- XDCx/XDCx.go
- XDCxlending/XDCxlending.go
Remove useless order.status assignment.
> chore: remove unnecessary order.status assignment

- core/vm/privacy/ringct.go
- core/vm/privacy/ringct_test.go
Fix the missing range check on signature range check
Core
> fix: missing validation in scalar range check

- params/version.go
> bump-version-2.0.2

- core/vm/privacy/ringct.go
- core/vm/privacy/ringct_test.go
- crypto/secp256k1/LICENSE
- crypto/secp256k1/curve.go
- crypto/secp256k1/dummy.go
- crypto/secp256k1/ext.h
- crypto/secp256k1/libsecp256k1/contrib/dummy.go
- crypto/secp256k1/libsecp256k1/dummy.go
- crypto/secp256k1/libsecp256k1/include/dummy.go
- crypto/secp256k1/libsecp256k1/src/asm/field_10x26_arm.s
- crypto/secp256k1/libsecp256k1/src/dummy.go
- crypto/secp256k1/libsecp256k1/src/modules/dummy.go
- crypto/secp256k1/libsecp256k1/src/modules/ecdh/dummy.go
- crypto/secp256k1/libsecp256k1/src/modules/recovery/dummy.go
- crypto/secp256k1/libsecp256k1/src/num.h
- crypto/secp256k1/libsecp256k1/src/secp256k1.c
- crypto/secp256k1/panic_cb.go
- crypto/secp256k1/scalar_mult_cgo.go
- crypto/secp256k1/scalar_mult_nocgo.go
- crypto/secp256k1/secp256.go
- crypto/secp256k1/secp256_test.go
- [ ✅] Bugfix (non-breaking change which fixes an issue)
> RIN-08 RIN-10 RIN-11  Fix curve issues

- consensus/XDPoS/engines/engine_v2/mining.go
- params/config.go
> lower log level for pretty log

- consensus/XDPoS/XDPoS.go
- consensus/XDPoS/engines/engine_v2/utils.go
Always check for err before returning values to avoid Panic Due to Dereferencing `nil`
> fix: always check for error value and return nil, err where possible

- core/vm/privacy/ringct.go
- core/vm/privacy/ringct_test.go
RIN-07 | Nil Pointer Dereference Panic Due to Missing Range Check of Signatures
> check parameters not to be nil when call function curve.Add

- core/vm/privacy/ringct_test.go
fix a test error in file core/vm/privacy/ringct_test.go which is caused by #424 and other PR.
> fix test error in file core/vm/privacy/ringct_test.go

- internal/debug/flags.go
> disable debug profile flag

- cicd/devnet/start.sh
- cicd/mainnet/start.sh
- cicd/testnet/start.sh
Update script to fix current devnet issue
> update start script to right syntax

- .github/workflows/ci.yml
- mobile/android_test.go
Since Travis free trail is ended. Change CI to use github action. Find github action can parallel running and super fast on each task.
> enable github action

- common/constants/constants.go.devnet
Enable shanghai for devnet on block 16832700 .
> Enable shanghai for devnet on block 16832700

- params/version.go
Bump Version to 2.1.0 and prepare release to testnet
> bump version to 2.1.0

- params/version.go
Bump to v2.2.0 as we will merge current dev-upgrade into master node
> bump to 2.2.0

- common/constants/constants.go.testnet
Enable ShanghaiBlock for solidity 0.8.23 testnet
Disable xdcx on testnet
Target date is Target 31st March 2024
> enable ShanghaiBlock and disable xdcx

- common/constants/constants.go.testnet
enable ShanghaiBlock and disable xdcx on testnet
> enable ShanghaiBlock and disable xdcx on testnet (#501)

- .github/workflows/ci.yml
continuation of https://github.com/XinFinOrg/XDPoSChain/pull/505
> fix calling parameters

- .github/workflows/deploy_rpc_image.yml
- cicd/terraform/module/ec2_rpc/main.tf
> Rpc volume

- .github/workflows/ci.yml
> fix blank output image name

- consensus/XDPoS/XDPoS.go
- consensus/XDPoS/engines/engine_v2/engine.go
- miner/worker.go
Remove uncle blocks handling as there should be no uncle blocks in XDPoS consensus design.
> remove uncle block handling

- core/bench_test.go
- core/state_transition.go
- core/tx_pool.go
- light/txpool.go
- params/protocol_params.go
revert eip2028 for sync problem.
> Revert "core, light, params: implement eip2028 (#19931)"

- consensus/XDPoS/engines/engine_v1/engine.go
revert future blocks check behavior for v1 engine due to sync issue
ref: https://github.com/XinFinOrg/XDPoSChain/pull/497
> revert future blocks check behavior for v1 engine

- params/version.go
> update release version string

- internal/ethapi/api.go
- internal/ethapi/trie_proof.go
- internal/ethapi/trie_proof_test.go
- internal/web3ext/web3ext.go
GetTransactionAndReceiptProof API
cf. https://github.com/XinFinOrg/XDC-Subnet/pull/94
> GetTransactionAndReceiptProof API

- common/constants.go
- params/version.go
> Rebase master into dev-upgrade

- cicd/terraform/main.tf
- cicd/terraform/module/ec2_rpc/main.tf
Increase ec2 volume since our internal mainnet rpc ran out of space.
> increase mainnet rpc volume

- cicd/devnet/start-local-devnet.sh
- cicd/devnet/start.sh
- cicd/mainnet/start.sh
- cicd/testnet/start.sh
remove admin for rpc and running node for security reason
> remove admin for rpc and running node

- cicd/ansible/playbooks/update-image.yaml
> add step to trigger rpc deployment script update

- contracts/validator/contract/XDCValidatorV2.sol
refactor function voteInvalidKYC and isOwner.
> refactor function voteInvalidKYC

- params/version.go
Add stable subfix keep the version more confident.
> add stable sufix in the mainnet version

- cicd/terraform/.env
> scale down devnet from 108 to 90

- cicd/devnet/terraform/.env
- cicd/terraform/.env
Downscale Devnet, previous pr is using wrong file.
> downscale devnet

- .github/workflows/ci.yml
terraform apply will deploy to latest image, doesn't need to do force deployment again.
> update devnet deployment script

- cicd/devnet/terraform/.env
scaling down devnet for cost saving.
> scale down devnet from 90 to 73

- common/constants.go
- consensus/XDPoS/engines/engine_v1/engine.go
- params/version.go
Merge from master to have mainnet fix commit 
> Merge from master

- internal/ethapi/api.go
- params/config.go
Merge from master for reorg bug fix
> Merge from master for reorg bug fix

- params/config.go
lower the devnet cert to 50% voting power to recover devnet
> lower the devnet cert to recover devnet

- cicd/devnet/terraform/.env
> Scale down devnet from 73 to 62

- core/blockchain.go
If node exit abnormally because `UpdateM1()` return error during reorg, the database become corrupted. When we start node at this time, the node will complain:
```text
Fatal: Error starting protocol stack: missing block number for head header hash
```
This PR keep database in normal state when `UpdateM1()` fails by save the incoming blocks during reorg.
> fix database corrupt when UpdateM1 fails during reorg

- core/blockchain.go
If node exit abnormally because `UpdateM1()` return error during reorg, the database become corrupted. When we start node at this time, the node will complain:
```text
Fatal: Error starting protocol stack: missing block number for head header hash
```
This PR keep database in normal state when `UpdateM1()` fails by save the incoming blocks during reorg.
> make database no corrupt when UpdateM1 fails during reorg

- cicd/devnet/terraform/.env
reduce devnet from 63 to 53 for cost saving
> reduce devnet from 63 to 53 for cost saving

- cicd/terraform/main.tf
Upgrade Devnet RPC instance type for support more and more rpc calls
> upgrade devnet rpc seems its cpu is reaching 100

- contracts/utils.go
> change Signer reward to debug

- cicd/ansible/playbooks/update-image.yaml
> revert fixed image

- core/vm/eips.go
The PR refactor the function EnableEIP in package vm.
Reference: #20958
> improve function EnableEIP in package vm

- consensus/XDPoS/XDPoS.go
- consensus/XDPoS/engines/engine_v2/engine.go
Example to show the place to upgrade.
> right place to upgrade validator smart contract

- core/vm/contracts.go
This PR fixes Byzantium precompile population.
Reference: #22603
> fix Byzantium precompile population

- core/vm/contract.go
> avoid map lookups for accessing jumpdest analysis

- common/bitutil/compress_fuzz.go
- tests/fuzzers/bitutil/compress_fuzz.go
- tests/fuzzers/bn256/bn256_fuzz.go
- tests/fuzzers/runtime/runtime_fuzz.go
This PR picks below PRs from geth:
- #21829
- #22029
> move fuzzers out of core

- eth/peer.go
- params/config.go
intro new timeout to solve mainnet issue temporarly
> intro new timeout

- eth/bft/bft_handler.go
- internal/debug/flags.go
> Broadcast timeout syncinfo after verify 2

- consensus/XDPoS/engines/engine_v2/engine.go
- consensus/XDPoS/engines/engine_v2/forensics.go
- eth/peer.go
- internal/debug/flags.go
- params/config.go
- params/version.go
Fix boardcast cascading issue on timeout and syncinfo messages.
> Mainnet debug

- eth/peer.go
- params/version.go
Increase message buffer to prevent cascading messages on all the nodes.
> increase message buffer to keep message

- consensus/XDPoS/engines/engine_v2/engine.go
fix timeout skip condition to allow current round
> fix timeout skip condition

- params/version.go
> bump version to v2.2.3

- params/config.go
- params/version.go
> update to 1 min timeout

- cmd/XDC/main.go
- cmd/XDC/usage.go
- cmd/utils/flags.go
- eth/config.go
> cherry pick from #664

- consensus/tests/engine_v1_tests/helper.go
- consensus/tests/engine_v2_tests/helper.go
- core/chain_makers.go
- core/state/statedb.go
- core/state/statedb_test.go
- core/state_processor.go
- eth/api_tracer.go
- miner/worker.go
This PR removes BlockHash from statedb.
Refercence: #23126
> remove block hash from statedb

- XDCx/order_processor.go
- XDCxlending/XDCxlending.go
- XDCxlending/lendingstate/lendingitem.go
- XDCxlending/order_processor.go
- bmt/bmt.go
- contracts/trc21issuer/simulation/test/main.go
- core/blockchain.go
- core/blockchain_test.go
- core/lending_pool_test.go
- core/order_pool_test.go
- core/vm/privacy/bulletproof.go
- core/vm/privacy/ringct_test.go
- crypto/bn256/cloudflare/optate.go
- metrics/registry_test.go
- whisper/mailserver/server_test.go
- whisper/whisperv6/filter_test.go
This PR fixes staticcheck warning [SA4006: never used value](https://staticcheck.dev/docs/checks/#SA4006):
A value assigned to a variable is never read before being overwritten. Forgotten error check or dead code?
> all: fix staticcheck warning SA4006: never used value

- XDCxDAO/mongodb.go
This PR fixes staticcheck warning [S1034: use result of type assertion to simplify cases](https://staticcheck.dev/docs/checks#S1034).
>  XDCxDAO: fix staticcheck warning S1034: use result of type assertion to simplify cases

- consensus/tests/engine_v1_tests/helper.go
- consensus/tests/engine_v2_tests/helper.go
- core/blockchain_test.go
- core/chain_makers.go
- core/state/journal.go
- core/state/statedb.go
- core/state/statedb_test.go
- core/state/transient_storage.go
- core/state_processor.go
- core/state_transition.go
- core/vm/eips.go
- core/vm/instructions.go
- core/vm/instructions_test.go
- core/vm/interface.go
- core/vm/opcodes.go
- core/vm/runtime/runtime.go
- eth/api_tracer.go
- miner/worker.go
- Implements TSTORE and TLOAD as specified by the following EIP:
- https://eips.ethereum.org/EIPS/eip-1153
- https://ethereum-magicians.org/t/eip-1153-transient-storage-opcodes/553
Reference: 
- #26003
- #27613
> all: implement EIP-1153(transient storage)

- miner/worker.go
> update log format

- cmd/XDC/chaincmd.go
- cmd/XDC/consolecmd.go
- cmd/XDC/main.go
- cmd/faucet/faucet.go
- console/console_test.go
- node/config_test.go
- node/node.go
- node/node_example_test.go
- node/node_test.go
- node/service_test.go
- p2p/simulations/adapters/inproc.go
- p2p/simulations/network.go
This PR is take on fixing the AccountsManager leak on node
> node, p2p/simulations: fix node.Node AccountsManager leak

- cicd/devnet/start.sh
- cicd/mainnet/start.sh
- cicd/testnet/start.sh
> add store-reward flag by default

- cicd/devnet/start.sh
> change devnetstats url

- cicd/devnet/start-local-devnet.sh
- cicd/devnet/start.sh
> fix typo and local script

- accounts/abi/bind/bind.go
- cmd/faucet/website.go
- eth/tracers/internal/tracers/assets.go
- ethstats/ethstats.go
- internal/jsre/deps/bindata.go
- p2p/nat/natupnp_test.go
This PR replaces `strings.Replace` with `string.ReplaceAll`.
Ref: #24835
> all: replace strings.Replace with string.ReplaceAll

- cmd/XDC/main.go
This PR fixed the bug of double metrics collect process.
> cmd/XDC: fix double metrics collect process issue

- core/blockchain.go
This PR removes unused functions and variables in the file `core/blockchain.go`.
```go
if bc.chainConfig.IsTIPXDCXReceiver(commonBlock.Number()) && bc.chainConfig.XDPoS != nil && commonBlock.NumberU64() > bc.chainConfig.XDPoS.Epoch {
bc.reorgTxMatches(deletedTxs, newChain)
}
```
The condition `bc.chainConfig.IsTIPXDCXReceiver(commonBlock.Number())` is never satisfied in the function `reorg` now. 
> core: remove unused functions and variables

- Makefile
- build/ci.go
- build/tools/tools.go
- go.mod
- go.sum
This PR adds a checker for 'go generate' which can be called by `make check_generate`.
> build: add checker for 'go generate' 

- .github/workflows/ci.yml
fix deploy script to ignore deployment not found
> fix deploy command

- core/types/receipt.go
This PR fixes the issue #812. 
> core/types: remove extra byte when EncodeRLP for Receipt

- accounts/keystore/key.go
- accounts/keystore/keystore_plain_test.go
> accounts/keystore: fix xdc-prefix address bug

- common/constants.go
- common/constants/constants.go.devnet
- common/constants/constants.go.local
- common/constants/constants.go.testnet
- eth/backend.go
- les/backend.go
- params/config.go
This PR:
- add Cancun blocks for solidity v0.8.24, Ref: #25305
- log chain config a bit saner, Ref: #24904
> params: add Cancun blocks and improve the output of chain config

- .github/workflows/ci.yml
> add backup rpc to cicd

- consensus/XDPoS/engines/engine_v2/forensics.go
- consensus/tests/engine_v2_tests/mine_test.go
- contracts/utils_test.go
- internal/ethapi/api.go
remove extra hash and string conversions
> consensus, internal, contracts: remove extra hash and string conversions

- core/state/state_object.go
- core/state/statedb.go
- core/vm/eips.go
- core/vm/instructions.go
- core/vm/interface.go
- core/vm/jump_table.go
This PR implements [EIP 6780](https://eips.ethereum.org/EIPS/eip-6780).
Ref: #27189
> core/state, core/vm: implement EIP 6780

- cmd/XDC/chaincmd.go
- core/genesis.go
- core/rawdb/accessors_chain.go
- core/rawdb/database.go
- core/rawdb/schema.go
- core/state/statedb_test.go
- eth/backend.go
- les/backend.go
- light/nodeset.go
- node/service.go
- node/service_test.go
> all: clean up and properly abstract database accesses

- eth/downloader/downloader.go
This PR fixes 2 bugs in `eth/downloader`.
Ref:
- #16509
- #16546
> eth/downloader: fix 2 bugs

- core/blockchain.go
- params/config.go
This PR prints more details of chain configuration. The new format is as follows:
```text
Chain configuration:
- ChainID:                     51
- Homestead:                   1
- DAO Fork:                    <nil>
- DAO Support:                 false
- Tangerine Whistle (EIP 150): 2
- Spurious Dragon (EIP 155):   3
- Byzantium:                   4
- Constantinople:              <nil>
- Petersburg:                  <nil>
- Istanbul:                    <nil>
- Berlin:                      61290000
- London:                      61290000
- Merge:                       61290000
- Shanghai:                    61290000
- Eip1559:                     9999999999
- Cancun:                      9999999999
- Engine:                      XDPoS
- Period: 2
- Epoch: 900
- Reward: 5000
- …
```
> params: print chain configuration in more detail

- XDCx/tradingstate/orderitem.go
- XDCx/tradingstate/relayer_state.go
- XDCxlending/lendingstate/lendingcontract.go
- XDCxlending/lendingstate/lendingitem_test.go
- XDCxlending/lendingstate/relayer.go
- common/constants.devnet.go
- common/constants.go
- common/constants.local.go
- common/constants.mainnet.go
- common/constants.testnet.go
- common/constants/constants.go.devnet
- common/constants/constants.go.local
- common/constants/constants.go.testnet
- common/types.go
- consensus/XDPoS/api.go
Removed unnecessary string conversions, using binary forms of special addresses for direct bit comparisons to cut conversion costs and speed up comparisons.
> performance: remove extra conversions

- core/state_transition.go
- core/txpool/list.go
- core/txpool/txpool.go
- core/types/transaction.go
- internal/ethapi/api.go
This PR:
- fixes issue #871
- improve function IsSpecialTransaction()
- remove some unused error variables in file `core/types/transaction.go`
> core: fix special tx cause debug API fail after EIP-1559

- eth/filters/filter_system_test.go
This PR picks #23619 from geth.
> eth/filters: fix TestPendingLogsSubscription

- eth/downloader/downloader.go
> eth/downloader: fix data race in downloader

- eth/gasprice/feehistory.go
This PR fixes deserialization error for foundry. When I use foundry:
```shell
forge create --broadcast --use solc:0.8.23 --rpc-url ${RPC} --private-key ${PRIVATE_KEY} --gas-price 12500000000 src/Counter.sol:Counter
forge create --broadcast --use solc:0.8.23 --rpc-url ${RPC} --private-key ${PRIVATE_KEY} --priority-gas-price 0 src/Counter.sol:Counter
```
Sometimes forge returns the following error:
```text
Error: Failed to estimate EIP1559 fees. This chain might not support EIP1559, try adding --legacy to your command.
Context:
- deserialization error: invalid value: string "-0x2e90edd00", expected a 16 byte hex string at line 1 column 71
```
After debug, I find:
forge request:
```json
{"jsonrpc":"2.0","id":3,"method":"eth_feeHistory","params":["0xa","latest",[20.0]]}
```
XDC response: …
> eth/gasprice: fix deserialization error for foundry

- eth/gasprice/feehistory.go
- eth/gasprice/feehistory_test.go
This PR improves the function `FeeHistory`. It pickes the following PRs from geth:
- #29644
- #31270
> eth/gasprice: improve function FeeHistory

- core/blockchain.go
> core: initialize current block/fastblock atomics to nil 

- core/blockchain_test.go
- core/chain_makers.go
- core/dao_test.go
- core/genesis.go
- eth/filters/filter_system_test.go
This PR 
- improve the function `Genesis.Commit`
- fix some testcases
> core: improve commit genesis

- common/constants.all.go
- common/constants.devnet.go
- common/constants.local.go
- common/constants.mainnet.go
- common/constants.testnet.go
- common/constants/constants.go.devnet
- common/constants/constants.go.local
- common/constants/constants.go.testnet
- params/config.go
- define cancun block for testnet 
- print chain config more detail
- rearrange some constants
> common, params: define cancun block for testnet and print more chain config 

- Makefile
update `Makefile`:
- add a new target `devtools`, usage: `make devtools`
- add a new target `help`, usage: `make help`
- remove target: gc
- reorganization and cleanup of existing targets and variables
> Makefile: add devtools and help targets, remove gc target

- console/console.go
- internal/jsre/completion.go
> console, internal/jsre: fix autocomplete issue

- trie/committer.go
lint file `trie/committer.go`
Ref: #21329
> trie: quell linter warnings in commiter.go #21329

- core/txpool/txpool.go
fix pending tx for non-local tx with zero tip 
> core/txpool: accept non-local transaction with zero tip

- p2p/server_test.go
> p2p: fix goroutine leaks in unit tests #20666

- rpc/client_test.go
- rpc/handler.go
- rpc/subscription.go
- rpc/websocket_test.go
> rpc: tighter shutdown synchronization in client subscription #22597

- rpc/types.go
- rpc/types_test.go
> rpc: implement JSON marshaling of BlockNumber #23324

- rpc/websocket.go
- rpc/websocket_test.go
> rpc: set pong read deadline #23556

- core/vm/contracts_test.go
- p2p/server_test.go
- rpc/websocket_test.go
> all: fix warning of DeepEqual on error #23624

- rpc/client.go
> rpc/client: fix typo #23834

- rpc/client.go
> rpc: linear time batch response matching #23856

- rpc/handler.go
> rpc: fix time key collision for logger with json output #24112

- internal/jsre/jsre_test.go
- node/node_test.go
- rpc/client_test.go
- rpc/websocket_test.go
> internal/jsre, node, rpc: fix goroutine leaks in tests #24211

- rpc/http.go
> rpc: set Request.GetBody for client requests #24292

- rpc/client.go
- rpc/subscription.go
> rpc: fix godoc #24488

- rpc/server_test.go
> rpc: fix defer in test #24490

- XDCx/XDCx.go
- XDCxlending/XDCxlending.go
- consensus/XDPoS/XDPoS.go
- consensus/clique/clique.go
- eth/backend.go
- internal/ethapi/backend.go
- node/api.go
- node/rpcstack.go
- node/utils_test.go
- rpc/types.go
> all: remove public field from rpc.API #25059

- cmd/XDC/main.go
- cmd/utils/flags.go
- node/endpoints.go
- node/rpcstack.go
- rpc/http.go
> cmd, node, rpc: add ReadHeaderTimeout config option #25338

- rpc/json.go
- rpc/subscription_test.go
- rpc/testdata/invalid-badversion.js
> rpc: check that version is 2.0 in request objects #25570

- rpc/websocket.go
This is to cater for more node providers.
geth: #26253
> rpc: decrease websocket ping interval #26253

- rpc/websocket_test.go
fix https://github.com/XinFinOrg/XDPoSChain/pull/978
> rpc, internal/guide: speed up tests a bit #26193

- node/api_test.go
- node/endpoints.go
- node/node.go
- node/node_test.go
- node/rpcstack.go
- node/rpcstack_test.go
- p2p/simulations/adapters/inproc.go
- rpc/client.go
- rpc/errors.go
- rpc/handler.go
- rpc/http.go
- rpc/json.go
- rpc/server.go
- rpc/subscription.go
- rpc/types.go
- rpc/websocket.go
> node, rpc: improve HTTP write timeout handling #25457

- core/blockchain.go
- core/blockchain_insert.go
> core: rework blockchain import and fix error in block iterator

- node/rpcstack_test.go
> node: ensure resp.body closed #26969

- rpc/client.go
- rpc/server.go
> rpc: use atomic types #27214

- rpc/websocket.go
> rpc: websocket should respect the HTTP_PROXY by default #27264

- eth/filters/api_test.go
- eth/filters/filter.go
- eth/filters/filter_test.go
- ethclient/ethclient.go
- ethclient/gethclient/gethclient.go
- rpc/types.go
> rpc: change BlockNumber constant values to match ethclient #27219

- cmd/XDC/main.go
- cmd/utils/flags.go
- node/api.go
- node/config.go
- node/defaults.go
- node/node.go
- node/rpcstack.go
- node/rpcstack_test.go
- rpc/client.go
- rpc/client_opt.go
- rpc/client_test.go
- rpc/errors.go
- rpc/handler.go
- rpc/http.go
- rpc/inproc.go
- rpc/ipc.go
- rpc/server.go
- rpc/server_test.go
- rpc/stdio.go
- rpc/testdata/invalid-batch-toolarge.js
- rpc/websocket.go
> rpc: add limit for batch request and response size #26681

- rpc/client.go
- rpc/errors.go
- rpc/handler.go
- rpc/subscription.go
> rpc: add method to test for subscriptions #25942

- rpc/websocket.go
> rpc: attempt to fix ping/pong logic race #27733

- go.mod
- go.sum
- rpc/ipc_windows.go
This PR replaces the old npipe implementation with official microsoft-code: https://github.com/microsoft/go-winio/
We're trying a new named pipe library, which should hopefully fix some occasional failures in CI.
geth: #27972
> rpc: use go-winio for named pipes #27972

- rpc/server_test.go
> rpc: fix erroneous error-message in test #28227

- rpc/websocket_test.go
> rpc: increase timeout in TestClientWebsocketPing #28371

- cmd/p2psim/main.go
- p2p/nat/nat.go
- p2p/simulations/http.go
- rpc/json.go
- rpc/service.go
> all: replace some cases of strings.SplitN with strings.Cut #28446

- core/state/statedb_test.go
- rpc/client_test.go
> core, rpc: speed up tests #28461

- rpc/client.go
- rpc/handler.go
- rpc/json.go
- rpc/server.go
- rpc/service.go
- rpc/subscription.go
- rpc/types.go
> rpc: fix typo

- rpc/http.go
> rpc: fix leak by close http body #29223

- rpc/websocket.go
> rpc: implement Unwrap() for wsHandshakeError #29522

- rpc/client_test.go
- rpc/websocket_test.go
> rpc: close Clients in tests #29512

- rpc/client.go
- rpc/client_test.go
- rpc/subscription.go
> rpc: add timeout to rpc client Unsubscribe #30318

- rpc/client_test.go
- rpc/http_test.go
- rpc/server_test.go
- rpc/subscription_test.go
- rpc/types_test.go
- rpc/websocket_test.go
> rpc: run tests in parallel #30384

- eth/api_tracer.go
- eth/downloader/api.go
- eth/filters/api.go
- node/api.go
- p2p/simulations/http_test.go
- rpc/subscription.go
- rpc/testservice_test.go
> rpc: remove deprecated method Notifier.Closed #29162

- consensus/XDPoS/api.go
Refactored the GetMasternodesByNumber function for improved readability and maintainability. The logic for calculating epochNum and collecting masternode, penalty, and standby node information has been streamlined. This update helps remove redundant code and clarifies the construction of the MasternodesStatus struct.
What types of changes does your code introduce to XDC network? Put an ✅ in the boxes that apply
> add-epoch-number-for-XDPoS_getMasternodesByNumber

- common/types.go
- consensus/XDPoS/api.go
- internal/web3ext/web3ext.go
add new api XDPoS_getRewardByAccount
> add new api XDPoS_getRewardByAccount

- docs/README.md
- docs/xdc/validator.md
add document for [XDCValidator.sol](https://github.com/XinFinOrg/XDPoSChain/blob/f041ad5a9b32e30af53ea0a5105b22d827045b51/contracts/validator/contract/XDCValidator.sol)
> docs: add document for contract XDCValidator

- node/node.go
Adds an INFO line about successfully reading the JWT secret
> node: add JWT secret log line #25095

- README.md
- docs/README.md
- docs/xdc/jsonrpc.md
add document for modules:
- XDPoS
- admin
- debug
- eth
- miner
- net
- personal
- rpc
- txpool
> docs: add document for JSONRPC API

- trie/sync.go
This PR checks nil bloom before use it.
> trie: check nil bloom

- XDCx/tradingstate/state_liquidationprice.go
- XDCx/tradingstate/state_orderbook.go
- XDCx/tradingstate/statedb.go
- XDCxlending/lendingstate/state_lendingbook.go
- XDCxlending/lendingstate/statedb.go
- core/state/statedb.go
- core/state/sync.go
- eth/downloader/downloader.go
- trie/committer.go
- trie/sync.go
- trie/trie.go
> core/state, eth, trie: stabilize memory use, fix memory leak #21491

- cmd/XDC/accountcmd_test.go
- internal/cmdtest/test_cmd.go
- node/rpcstack.go
- trie/trie_test.go
> all: fix tests on 32-bit and windows + minor rpc fixes #21871

- go.mod
- go.sum
- trie/sync_bloom.go
This PR switches bloom filter, from the (archived) steakknife implementation a much much better (faster + less false positives) one.
Ref: #22044
> trie: use github.com/holiman/bloomfilter/v2 #22044

- trie/sync.go
> trie: fix bloom crash on fast sync restart #22332

- trie/iterator.go
- trie/iterator_test.go
> trie: improve the node iterator seek operation #22470

- trie/proof.go
- trie/proof_test.go
> trie: extend range proof #21250

- XDCx/tradingstate/state_liquidationprice.go
- XDCx/tradingstate/state_orderbook.go
- XDCx/tradingstate/statedb.go
- XDCxlending/lendingstate/state_lendingbook.go
- XDCxlending/lendingstate/statedb.go
- core/state/statedb.go
- core/state/sync.go
- core/state/sync_test.go
- eth/downloader/statesync.go
- trie/committer.go
- trie/sync.go
- trie/trie.go
- trie/trie_test.go
> trie: faster snapshot generation #22504

- trie/iterator.go
> trie: reuse memory data instead of hitting disk when generating #22667

- trie/iterator.go
- trie/sync.go
> trie: fix typos

- XDCxDAO/interfaces.go
- XDCxDAO/leveldb.go
- XDCxDAO/mongodb.go
- core/rawdb/table.go
- ethdb/batch.go
- ethdb/leveldb/leveldb.go
- ethdb/memorydb/memorydb.go
- tests/fuzzers/bn256/bn256_fuzz.go
- trie/iterator_test.go
- trie/trie_test.go
> all: implement NewBatchWithSize API for batcher #24392

- core/types/hashing_test.go
- trie/trie_test.go
> core, trie: change format 0x%x to %#x #25221

- trie/hasher.go
> trie: fix parallel typo in trie/hasher.go #25241

- .github/workflows/ci.yml
make cicd apply to new RPC deployments
> update new rpcs to cicd

- core/state/sync_test.go
- eth/downloader/statesync.go
- trie/secure_trie.go
- trie/sync.go
- trie/sync_test.go
- trie/trie.go
> core, eth, trie: prepare trie sync for path based operation #21504

- node/rpcstack_test.go
upgrade the node package
Ref: #21481
> node: support expressive origin rules in ws.origins #21481

- node/rpcstack.go
upgrade the node package
Ref: #22307
> node: show websocket url in logs #22307

- node/api.go
- node/node.go
upgrade the node package
Ref: #25939
> node: prevent exposing engine API on unauthenticated endpoint #25939

- trie/encoding_test.go
- trie/trie_test.go
> trie: remove deprecated uses of math.rand

- node/config.go
- node/node.go
> node: drop support for static & trusted node list files #25610

- internal/debug/flags.go
- node/config.go
- node/rpcstack.go
> node: allow listening on IPv6 address #27635

- cicd/devnet/start.sh
- cicd/mainnet/start.sh
- cicd/testnet/start.sh
> turn off personal, debug, shh apis by default

- consensus/misc/eip1559/eip1559.go
- eth/tracers/tracer.go
- internal/ethapi/api.go
- internal/ethapi/transaction_args_test.go
- node/rpcstack.go
> all: replace fmt.Errorf() with errors.New() if no param required #29126

- accounts/abi/unpack_test.go
- core/rawdb/accessors_chain_test.go
- internal/flags/flags_test.go
> all: update to golangci-lint 1.61.0 #30587

- build/ci.go
- internal/build/util.go
- internal/jsre/jsre_test.go
- node/node_auth_test.go
> all: replace path.Join with filepath.Join #29479

- core/state/statedb.go
- eth/api_tracer.go
> core, eth: fix tracer dirty finalization #16588

- XDCx/tradingstate/state_liquidationprice.go
- XDCx/tradingstate/state_orderbook.go
- XDCx/tradingstate/statedb.go
- XDCxlending/lendingstate/statedb.go
- consensus/XDPoS/engines/engine_v1/engine.go
- consensus/clique/clique.go
- core/state/state_object.go
> XDCx, consensus: fix some typos

- core/state/statedb.go
- core/state/statedb_test.go
> core/state: memory efficient, add AddPreimage test #16663

- trie/proof.go
- trie/proof_test.go
> trie: fix range prover #22210

- core/state/statedb_test.go
> core/state: fix db test random args #19255

- core/state/statedb_test.go
> core/state: avoid unnecessary conversions #19870

- core/state/state_object.go
> core/state: fix state object deep copy #20100

- core/state/statedb_test.go
> core/state: revert noop finalise, fix copy-commit-copy #20113

- core/state/statedb_test.go
> core/state: fix database leak and copy tests #19306

- core/rawdb/accessors_state.go
> core/rawdb: do prefixed lookup first #24288

- core/rawdb/accessors_state.go
> core/rawdb: add func HasCodeWithPrefix and HasTrieNode #24117

- core/blockchain.go
- core/state/state_object.go
- core/state/statedb.go
> core: rename CommitTrie to commitTrie #25896

- core/state/statedb.go
- core/state/statedb_test.go
- core/state_processor.go
> core: fill blockNumber in logs #26345

- core/vm/instructions.go
> core/vm: minor code formatting #28199

- core/state_transition.go
- core/vm/evm.go
> core/vm: set basefee to 0 internally on eth_call #28470

- trie/trie_test.go
> trie: move fuzzers into native packages #28467

- .github/workflows/ci.yml
since new nodes are added to Devnet, running update command 1 by 1 is not feasible, use loop to update every kubernetes depoyment/devnet*
> Update Devnet CICD

- crypto/signature_cgo.go
- crypto/signature_nocgo.go
> crypto: use pure Go signature implementation in tinygo #31878

- crypto/bn256/gnark/g1.go
- crypto/bn256/gnark/g2.go
- crypto/bn256/gnark/native_format_test.go
> crypto/bn256: fix gnark deserialisation #32055

- crypto/bn256/cloudflare/twist.go
- crypto/bn256/google/twist.go
> crypto/bn256: add documentation on subgroup checks for G2 #32066

- core/vm/contract.go
- core/vm/contracts_test.go
- core/vm/gas_table.go
- core/vm/interpreter.go
- core/vm/jump_table_export.go
- core/vm/jump_table_test.go
- core/vm/operations_acl.go
- core/vm/runtime/runtime_test.go
fixes various typos in core
Ref:
- #28255
- #28682
- #28743
> core: fix typos

- core/vm/instructions.go
> core: using math.MaxUint64 instead of 0xffffffffffffffff #29022 #29024

- core/vm/operations_acl.go
> core/vm: prevent overflow #29023

- eth/tracers/tracer_test.go
fix function comments in the file `eth/tracers/tracer_test.go`
> eth/tracers: fix comments

- consensus/ethash/ethash.go
- eth/tracers/tracer.go
remove redundant import names
Ref: #21903
> consensus, eth/tracers: remove redundant import names #21903

- eth/api_tracer.go
- eth/tracers/testing/calltrace_test.go
- eth/tracers/tracer.go
- eth/tracers/tracer_test.go
- eth/tracers/tracers.go
- eth/tracers/tracers_test.go
> eth/tracers: expose gas used in tx to js tracer #22038

- eth/api_tracer.go
> eth: make tracers respect pre-EIP158/161 rules #18503

- trie/notary.go
- trie/proof.go
- trie/proof_test.go
> trie: remove redundant returns + use stacktrie where applicable #22760

- trie/database.go
> trie: remove the duplicate write for preimage #23001

- core/state/dump.go
- trie/iterator.go
> core, trie: decode the value for storage dump #19943

- cmd/XDC/chaincmd.go
- cmd/XDC/config.go
> cmd/XDC: fixes db unavailability for chain commands #21415

- XDCx/tradingstate/XDCx_trie.go
- XDCxlending/lendingstate/XDCx_trie.go
- core/state/database.go
- core/state/metrics.go
- core/state/state_object.go
- core/state/statedb.go
- trie/committer.go
- trie/iterator_test.go
- trie/proof.go
- trie/secure_trie.go
- trie/trie.go
- trie/trie_test.go
> core, trie: add state metrics #23433

- core/block_validator.go
- core/state/statedb.go
- core/vm/interface.go
> core: show db error-info in case of mismatched hash root #26870

- core/state/iterator.go
- core/state/iterator_test.go
- core/state/sync_test.go
> core/state: unexport NodeIterator #27239

- trie/trie.go
> trie: better error-handling #23657

- core/rawdb/accessors_state.go
> core/rawdb: add HasCode, HasTrieNode and use them where possible #24454

- core/state/dump.go
- eth/api.go
- eth/api_test.go
> eth: add debug_accountRange API #19645

- core/genesis.go
> core: fix deprecation comment for GenesisAccount #29218

- internal/web3ext/web3ext.go
> internal/web3ext: add eth_getLogs to console #24297

- internal/web3ext/web3ext.go
Ref:
- #26265 
- #26266 
- #26268
> internal/web3ext: fix eth_call in console #26265 #26266 #26268

- ethclient/ethclient.go
- ethclient/ethclient_test.go
> ethclient: include block hash from FilterQuery #17996

- eth/api_backend.go
> add error when accessing missing block state #18346

- ethclient/ethclient.go
> ethclient: fix parity compatibility on newHeads #16454

- trie/sync.go
> core, trie: use db.has over db.get where possible #24117

- trie/proof.go
> trie: fix range prover #24266

- trie/proof_test.go
Ref: #24257
Notice: This PR needs #24266
> trie: test for edgecase in VerifyRangeProof #24257

- .github/workflows/ci.yml
activate devnet cicd and use selective deployment
> devnet cicd selective deployment

- eth/tracers/api_test.go
> eth/tracers: backend for 1559 #23038

- ethclient/ethclient.go
> ethclient: add BlockNumber method #21500 #21565

- ethclient/ethclient.go
- ethclient/signer.go
> ethclient: fix tx sender cache miss detection #23877

- trie/committer.go
- trie/database.go
> trie: move locking into trieDB insert method #25030

- cmd/XDC/chaincmd.go
- cmd/evm/runner.go
- cmd/evm/staterunner.go
- cmd/utils/flags.go
- core/rawdb/accessors_chain.go
- core/state/dump.go
- core/state/state_test.go
- eth/api.go
- eth/api_test.go
> all: snapshot dump + unify with trie dump #22795

- eth/tracers/api.go
- eth/tracers/api_test.go
- eth/tracers/testing/calltrace_test.go
- eth/tracers/tracer.go
- eth/tracers/tracer_test.go
- eth/tracers/tracers.go
- eth/tracers/tracers_test.go
> eth/tracers: expose contextual infos (block hash, tx hash, tx index) #23104

- ethclient/gethclient/gethclient.go
> ethclient: return storage proofs in GetProof #24697

- ethclient/ethclient.go
> ethclient: add PeerCount method #24849

- ethclient/gethclient/gethclient.go
> ethclient/gethclient: fix bugs in override object encoding #25616

- core/blockchain.go
This PR sends a HeadChainEvent on SetHead. The txpool will reset the txnoncer on receiving this head chain event.
closes https://github.com/ethereum/go-ethereum/issues/26154 & https://github.com/ethereum/go-ethereum/issues/20078
Ref: #26392
> core: reset txpool on sethead #26392

- ethclient/ethclient.go
> ethclient: acquire the rpc.Client #27246

- ethclient/ethclient.go
> ethclient: fix BlockReceipts parameter encoding #28087

- ethclient/ethclient.go
> ethclient: allow calling contracts at a specific block hash #28084

- trie/stacktrie_test.go
> trie: lint whitespace #25312

- eth/api_backend.go
- eth/state_accessor.go
- eth/tracers/api.go
- eth/tracers/api_test.go
> eth: make traceChain avoid OOM on long-running tracing #23736

- ethclient/ethclient_test.go
> ethclient: replace noarg fmt.Errorf with errors.New #27334

- eth/filters/filter_system.go
> eth/filters: reuse func handleLogs for Removed logs #27438

- ethclient/ethclient.go
> ethclient: add RevertErrorData function #30669

- ethclient/ethclient.go
> ethclient: enhance the description of using block number tags #30984

- ethclient/ethclient.go
> ethclient: add EstimateGasAt[Hash] functions #27508

- ethclient/gethclient/gethclient.go
> ethclient/gethclient: add method TraceBlock #32092

- rlp/raw.go
> rlp: no need to repeat called len method #29936

- rlp/rlpgen/gen.go
- rlp/rlpgen/testdata/pkgclash.in.txt
- rlp/rlpgen/testdata/pkgclash.out.txt
> rlp/rlpgen: implement package renaming support #31148

- ethclient/gethclient/gethclient.go
> ethclient/gethclient: use common.Hash to debug_traceTransaction #32404

- XDCx/tradingstate/XDCx_trie.go
- XDCx/tradingstate/statedb_test.go
- XDCxlending/lendingstate/XDCx_trie.go
- XDCxlending/lendingstate/statedb_test.go
- core/state/database.go
- core/state/metrics.go
- core/state/state_object.go
- core/state/statedb.go
- internal/ethapi/trie_proof.go
- trie/committer.go
- trie/database.go
- trie/iterator.go
- trie/iterator_test.go
- trie/nodeset.go
- trie/proof.go
- trie/secure_trie.go
- trie/secure_trie_test.go
- trie/sync_test.go
- trie/trie.go
- trie/trie_test.go
- trie/util_test.go
Notice: This PR breaks the testcases `TestRevertStates` and `TestDumpState`. I didn't fix them since `XDCx` and `XDCxlending` have been abandoned.
Ref: #25320
> all: rework trie committer #25320

- XDCx/tradingstate/statedb.go
- XDCxlending/lendingstate/statedb.go
- core/blockchain.go
- core/state/database.go
- core/state/statedb.go
- eth/api.go
- eth/downloader/downloader_test.go
- trie/iterator_test.go
- trie/proof.go
- trie/secure_trie.go
- trie/secure_trie_test.go
- trie/sync_test.go
- trie/trie.go
> core, eth, trie: use TryGetAccount to read what TryUpdateAccount has written #25458

- rlp/encbuffer.go
> rlp: refactor to use maths.ReadBits #32432

- rpc/handler.go
- rpc/json.go
- rpc/websocket_test.go
> rpc: add method name length limit #31711

- rpc/server.go
- rpc/server_test.go
- rpc/websocket.go
> rpc: add SetWebsocketReadLimit in Server #32279

- accounts/abi/reflect.go
- accounts/abi/reflect_test.go
- accounts/abi/type.go
- accounts/keystore/keystore.go
> accounts/abi, accounts/keystore: use reflect.TypeFor #32323

- accounts/scwallet/wallet.go
> accounts/scwallet: fixes nil pointer dereference in scwallet #32186

- accounts/abi/abigen/source2.go.tpl
- accounts/abi/abigen/testdata/v2/crowdsale.go.txt
- accounts/abi/abigen/testdata/v2/dao.go.txt
- accounts/abi/abigen/testdata/v2/eventchecker.go.txt
- accounts/abi/abigen/testdata/v2/nameconflict.go.txt
- accounts/abi/abigen/testdata/v2/numericmethodname.go.txt
- accounts/abi/abigen/testdata/v2/overload.go.txt
- accounts/abi/abigen/testdata/v2/token.go.txt
- accounts/abi/abigen/testdata/v2/tuple.go.txt
- accounts/abi/bind/v2/internal/contracts/db/bindings.go
- accounts/abi/bind/v2/internal/contracts/events/bindings.go
> accounts/abi: fix panic when check event with log has empty or nil topics #32503

- crypto/secp256k1/curve.go
- crypto/secp256k1/scalar_mult_cgo.go
> crypto/secp256k1: use ReadBits from common/math #32430

- crypto/bn256/gnark/g1.go
- crypto/bn256/gnark/g2.go
> crypto/bn256: refactor to use bitutil.TestBytes #32435

- ethstats/ethstats.go
> ethstats: fix golint warning #16837

- ethstats/ethstats.go
> ethstats: fix comment typo #17102

- ethstats/ethstats.go
> ethstats: stop report ticker in each loop cycle #21071

- eth/tracers/logger/gen_structlog.go
- eth/tracers/logger/logger.go
- eth/tracers/logger/logger_test.go
> eth/tracers/logger: use omitempty to reduce log bloat #24547

- eth/tracers/native/revertreason.go
> eth/tracers: add initial revertReasonTracer tracer #25265

- eth/tracers/js/goja.go
- eth/tracers/js/tracer_test.go
> eth/tracers: add onlyTopCall option to callTracer #25430

- eth/tracers/api.go
- eth/tracers/logger/logger.go
- eth/tracers/native/4byte.go
- eth/tracers/native/call.go
- eth/tracers/native/mux.go
> eth/tracers: add multiplexing tracer #26086

- eth/tracers/native/4byte.go
- eth/tracers/native/call.go
- eth/tracers/native/prestate.go
> eth/tracers: small refactor for native tracers #26196

- eth/tracers/api.go
- eth/tracers/api_test.go
> eth/tracers: return proper error from debug_TraceTransaction when tx not found #26211

- eth/api.go
- eth/api_backend.go
- eth/state_accessor.go
- eth/tracers/api.go
> eth: add request cancellation checks #26320

- eth/tracers/internal/tracetest/calltrace_test.go
- eth/tracers/native/call.go
- eth/tracers/native/gen_callframe_json.go
> eth/tracer: rename to revertReason #26574

- eth/tracers/internal/tracetest/calltrace_test.go
- eth/tracers/js/goja.go
- eth/tracers/js/tracer_test.go
- eth/tracers/native/call.go
- eth/tracers/native/prestate.go
- eth/tracers/tracers.go
- eth/tracers/tracers_test.go
> eth/tracers/native: prevent panic for LOG edge-cases #26848

- eth/tracers/js/goja.go
- eth/tracers/logger/logger_test.go
- eth/tracers/tracers.go
> eth/tracers: replace noarg fmt.Errorf with errors.New #27330

- eth/tracers/js/goja.go
> eth/tracers: refactor exporting js buffer #27472

- common/types.go
- eth/tracers/api_test.go
> eth/tracers: use slices package for sorting #27490

- eth/tracers/native/call_flat.go
> eth/tracers/native: replace instances of suicide with selfdestruct #27716

- eth/tracers/api.go
- eth/tracers/api_test.go
> eth/tracers: support debug_traceCall on transaction #28460

- eth/tracers/js/internal/tracers/call_tracer_legacy.js
- eth/tracers/tracers_test.go
> eth/tracers: fix typos in comments #28881

- core/blockchain.go
- trie/database.go
> core, trie: flush preimages to db on database close #25533

- core/state/database.go
- core/state/statedb.go
- trie/secure_trie.go
> core/state, trie: add DeleteAccount method #25531

- ethstats/ethstats.go
> ethstats: fix reconnection issue, implement primus pings #21347

- ethstats/ethstats.go
> ethstats: use timer instead of time.After in loops #29241

- eth/tracers/logger/access_list_tracer.go
> eth/tracers/logger: using maps.Equal #29384

- eth/tracers/js/goja.go
> eth/tracers/js: consistent name for method receivers #29375

- core/vm/errors.go
- core/vm/gas_table.go
- core/vm/gas_table_test.go
- core/vm/interpreter.go
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/callcode_precompiled_throw.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/nested_create_action_gas.json
> core/vm: better error-info for vm errors #29354

- eth/tracers/native/call_flat.go
- eth/tracers/native/call_flat_test.go
> eth/tracers/native: fix flatCallTracer Stop() bug #29623

- eth/tracers/api.go
> eth/tracers: fix #29800 #29811

- eth/downloader/api.go
- eth/tracers/api_test.go
> eth/downloader, eth/tracer: fix typos in comments #29707

- core/blockchain.go
- core/tracing/hooks.go
> core/tracing: add OnClose Trace Hook #29629

- eth/tracers/native/call_flat.go
> eth/tracers/native: remove unnecessary check #30071

- eth/tracers/internal/tracetest/makeTest.js
Ref: #30364
Fixes the tracer test filler for when there is tracerConfig.
>  eth/tracers/internal/tracetest: include tracerConfig in created tracing test #30364

- cmd/XDC/chaincmd.go
- cmd/XDC/main.go
- cmd/utils/flags.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
> cmd, eth: rename config and flag to VMTraceJsonConfig #29573

- contracts/XDCx/simulation/fee/trading/main.go
- contracts/multisigwallet/multisigwallet.go
- ethdb/database.go
> all: fix goimports

- eth/tracers/internal/tracetest/testdata/call_tracer_flat/callcode_precompiled_fail_hide.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/callcode_precompiled_oog.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/callcode_precompiled_throw.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/create_oog_parity.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/gas.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/nested_create.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/nested_create2_action_gas.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/nested_create_inerror.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/result_output.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/selfdestruct.json
- eth/tracers/internal/tracetest/testdata/call_tracer_flat/skip_no_balance_error.json
- eth/tracers/native/call_flat.go
> eth/tracers:  flatCallTracer error compatible with parity #30497

- eth/fetcher/fetcher.go
> eth/fetcher: fix copyloopvar for Go 1.22+

- cmd/XDC/accountcmd.go
- contracts/XDCx/simulation/fee/trading/main.go
- eth/filters/api.go
- eth/filters/filter_system_test.go
- eth/filters/filter_test.go
- p2p/simulations/http.go
> all: fix whitespace

- eth/tracers/logger/logger.go
> eth/tracers/logger: improve markdown logger #30805

- log/root.go
- log/root_test.go
> log: fix SetDefault for custom loggers #31368

- eth/tracers/logger/logger_json.go
> eth/tracers: fix json logger for evm blocktest #29795

- rlp/encode_test.go
> rlp: remove duplicate optionalAndTailField test case #32614

- contracts/utils.go
- contracts/validator/validator_test.go
- core/blockchain.go
- core/vm/privacy/bulletproof.go
> all: fix ineffectual assignment

- consensus/tests/engine_v2_tests/reward_test.go
- core/state/statedb_utils.go
- eth/hooks/engine_v2_hooks.go
fix: bug that minted token recorded value is zero
> all: fix minted token recorded value is zero

- cicd/Dockerfile
- cicd/local/start.sh
- cicd/puppeth.sh
- cmd/puppeth/puppeth.go
- cmd/puppeth/wizard.go
- cmd/puppeth/wizard_genesis.go
- cmd/puppeth/wizard_intro.go
- common/constants.all.go
- common/constants.local.go
- common/types.go
- contracts/validator/validator.go
- contracts/validator/validator_test.go
Changes to allow integration with chain deployment generator.
- private chain initialization fixes
- genesis improvment (puppeth)
- integrate with deployment genrator
> Improve genesis for easy privatechain deployment

- trie/database.go
- trie/hasher.go
- trie/proof_test.go
- trie/secure_trie_test.go
> trie: fix some typos #25551 #25648

- consensus/XDPoS/engines/engine_v2/forensics.go
- core/vm/privacy/bulletproof.go
- core/vm/privacy/ringct.go
- trie/trie.go
> all: fix govet

- accounts/abi/bind/v2/base.go
> accounts/abi/bind/v2: add Address method to BoundContract #32559

- internal/web3ext/web3ext.go
> internal/web3ext: enforce mixed caps variable names #19059

- console/console.go
> console: prevent importRawKey from getting into CLI history #21279

- console/bridge.go
> console: fix admin.sleepBlocks #21629

- cmd/XDC/accountcmd.go
- cmd/XDC/accountcmd_test.go
- cmd/ethkey/README.md
- cmd/ethkey/message_test.go
- cmd/ethkey/utils.go
> cmd: replace passPHRASE with passWORD in any user interactions #19932

- console/console.go
> console: fix some typos #25551

- console/console_test.go
> console: fix the wrong error msg of datadir testcase #29183

- event/feed_test.go
> event: add missing timer.Stop call in TestFeed #20868

- event/event_test.go
> event: fix goroutine leak #20667

- event/event.go
> event: fix inconsistency in Lock and Unlock #20933 #20940

- event/subscription.go
- event/subscription_test.go
> event: add ResubscribeErr #22191

- event/feedof.go
- event/feedof_test.go
> event: add FeedOf[T] #26310 #26803

- consensus/XDPoS/engines/engine_v2/forensics.go
- consensus/tests/engine_v2_tests/helper.go
> all: fix misspell

- common/hexutil/json_test.go
> common: remove duplicate test cases #32624

- core/blockchain.go
- eth/api.go
- internal/ethapi/api.go
> core, eth, internal: improve getBadBlocks to return full block rlp #16902

- trie/proof.go
- trie/secure_trie.go
- trie/stacktrie.go
- trie/trie.go
> trie: better error reporting #25645

- cmd/XDC/consolecmd_test.go
- console/console.go
> console: add note about typing exit #23602

- trie/sync.go
> trie: check childrens' existence concurrently for snap heal #25694

- cmd/XDC/consolecmd.go
> cmd: fix lint error mirror

- common/constants.all.go
Improve CopyConstants function
> common: use tagged switch on chainID in func CopyConstants 

- internal/ethapi/api.go
> internal/ethapi: add basefee to block overrides #25219

- internal/ethapi/api.go
extract function `doCall` from `DoCall` as geth
> internal/ethapi: refactor func DoCall

- accounts/abi/bind/backends/simulated.go
- core/token_validator.go
- eth/state_accessor.go
- eth/tracers/api.go
- eth/tracers/api_test.go
- internal/ethapi/api.go
This PR removes zero owner variables.
> all: eliminate zero owner variables

- cmd/utils/flags.go
- metrics/runtimehistogram.go
> all: refactor to use builtin max/min #32694

- consensus/XDPoS/engines/engine_v1/engine.go
- consensus/XDPoS/engines/engine_v2/engine.go
- consensus/clique/clique.go
- consensus/ethash/consensus.go
- consensus/tests/engine_v1_tests/helper.go
- consensus/tests/engine_v2_tests/helper.go
- core/genesis.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_indexes_test.go
- core/state_processor_test.go
- core/txpool/txpool_test.go
- core/types/block.go
- core/types/block_test.go
- eth/backend.go
- eth/downloader/downloader.go
- eth/downloader/queue.go
- eth/fetcher/fetcher.go
- eth/fetcher/fetcher_test.go
- ethclient/ethclient.go
- miner/worker.go
> all: refactor so `NewBlock`, `WithBody` take `types.Body` #29482

- consensus/XDPoS/engines/engine_v2/engine.go
fix audit issue XFN-09: Unsynchronized QC Verification Error Flag In Signature Verification
> engine_v2: fix unsynchronized QC verification Error, close XFN-09

- consensus/XDPoS/engines/engine_v2/verifyHeader.go
- consensus/ethash/consensus.go
fix audit issue XFN-07: Gas Limit Bounds Not Enforced in XDPoS Verification
> consensus: check gas limit bounds in header, close XFN-07
