contracts/validator/contract/ValidatorKyc.sol
now the owner length will reduce too once a person is deleted.
Its KYC count will be reset & can upload a KYC again if they choose too.
All arguments for voting  / getting data for invalidKYC has been tweaked to refer by candidates.
=> fixed : owner length; KYC reset enabled

common/constants.go, common/types.go, consensus/XDPoS/XDPoS.go, contracts/utils.go, core/blockchain.go, eth/backend.go, miner/worker.go, params/version.go
Send tx sign for block number to smart contract blockSigner.
Update signers in the snapshot
Ignore signerCheck at checkpoint block 27307800 due to the wrong snapshot at gap 27307799
=> Work around for the issue "return wrong list signers from snapshot" 

.gitignore, .travis.yml, cicd/devnet/start.sh, cicd/devnet/terraform/.terraform.lock.hcl, cicd/devnet/terraform/main.tf
- Add delay to the devnet docker image as the ECS fargate will take 30s to stop the previous deployed node. We will wait for 45s before start the new node.
- Add new terraform feature to create AWS infrastructures. This PR including VPC, subnet, Internet gateway, S3 bucket and other major initial setup.
=> Setup terraform 1

consensus/XDPoS/XDPoS.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/XDPoS/engines/engine_v2/verifyHeader.go, consensus/XDPoS/utils/utils.go, consensus/tests/engine_v2_tests/adaptor_test.go, consensus/tests/engine_v2_tests/verify_header_test.go, params/config.go
preventing case like: 
v1 blockchain already pass v2 switch block number, then node owner upgrade to v2, node should be able to re-snyc to latest v2 blocks
=> xin-244 re-snyc blocks from v1 to v2

.travis.yml
- Use docker hub instead of ECR for XDC docker images
=> XIN-245: Push devnet build image to docker hub

eth/handler.go
Currently to stop message scam, we put the message in the queue, and skip process if this message is already processed no matter its final status ( success or failure ). But here comes the case, the syncInfo message comes during synchronization. This is the problem, syncInfo comes along with latest round number which way ahead to mining nodes round number at sync point of time, so the message will get dropped because node filters out this kind of message.
Skip message processing during synchronising will help resolve this issue.
=> xin-250 skip process message whenever synchronising

cicd/devnet/terraform/ecs.tf
1024 units of memory was too small to handle XDC chain.
=> Increase devnet ECS memory

cmd/XDC/config.go, cmd/XDC/main.go, cmd/utils/flags.go, common/constants.go, common/types.go
Add a bool flag `--enable-0x-prefix`. This default value of this flag is false, and can be set to true when startup. The function `MarshalText` choose address prefix with this flag:
```go
func (a Address) MarshalText() ([]byte, error) {
// Handle '0x' or 'xdc' prefix here.
if (Enable0xPrefix) {
return hexutil.Bytes(a[:]).MarshalText()
} else {
return hexutil.Bytes(a[:]).MarshalXDCText()
}
}
```
=> add enable-0x-prefix flag

cmd/XDC/main.go, consensus/XDPoS/XDPoS.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/XDPoS/engines/engine_v2/epochSwitch.go, consensus/XDPoS/engines/engine_v2/timeout.go, consensus/XDPoS/engines/engine_v2/utils.go, consensus/XDPoS/engines/engine_v2/verifyHeader.go, consensus/XDPoS/engines/engine_v2/vote.go, consensus/XDPoS/utils/errors.go, consensus/tests/engine_v1_tests/helper.go, consensus/tests/engine_v2_tests/adaptor_test.go, consensus/tests/engine_v2_tests/authorised_masternode_test.go, consensus/tests/engine_v2_tests/helper.go, consensus/tests/engine_v2_tests/initial_test.go, consensus/tests/engine_v2_tests/reward_test.go, consensus/tests/engine_v2_tests/timeout_test.go, consensus/tests/engine_v2_tests/verify_header_test.go, core/blockchain.go, core/genesis.go, eth/hooks/engine_v2_hooks.go, miner/worker.go, params/config.go, params/config_test.go
Refactor getting `minePeriod` and `CertThreshold` config from whenever consensus version got chosen to whenever function needs it. This is the better way in terms of parallel computing or limit the scope, also fix the bug on `VerifyHeaders` function
* variables naming
* config refactor
* function refactor
* Log and error
* Config
* VerifyQC
=> Multi config bug fix

eth/api_backend.go, eth/backend.go, light/txpool.go, rpc/types.go
This PR creates a new `rpc.BlockNumber` type called `ConfirmedBlockNumber`, which serves to provide users access to the finalized block in V2.
=> Devnet Update Query

p2p/peer_error.go
Problem: https://github.com/advisories/GHSA-wjxw-gh3m-7pm5
Fix: add non-negative `if` condition.
cannot use fix in geth (https://github.com/ethereum/go-ethereum/pull/24507) since modifying DiscReason to uint8 messes up the message encode
=> Fix of discreason type problem

consensus/XDPoS/api.go, consensus/XDPoS/api_test.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/XDPoS/engines/engine_v2/epochSwitch.go, consensus/XDPoS/engines/engine_v2/utils.go, consensus/tests/engine_v2_tests/penalty_test.go, core/types/consensus_v2.go
* Fix API penalty bug, shouldn't call calcMasternodes on any block, it only valids on epoch switch block.
* Add block and round and err column for more informative. 
* Complete Test.
=> Fix API penalty bug and add more info in api

cmd/utils/flags.go, consensus/XDPoS/XDPoS.go, consensus/XDPoS/XDPoS_test.go, consensus/XDPoS/engines/engine_v1/engine.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/tests/engine_v1_tests/block_signer_test.go, consensus/tests/engine_v2_tests/adaptor_test.go, consensus/tests/engine_v2_tests/authorised_masternode_test.go, consensus/tests/engine_v2_tests/helper.go, consensus/tests/engine_v2_tests/initial_test.go, consensus/tests/engine_v2_tests/mine_test.go, consensus/tests/engine_v2_tests/proposed_block_test.go, consensus/tests/engine_v2_tests/timeout_test.go, consensus/tests/engine_v2_tests/verify_blockinfo_test.go, consensus/tests/engine_v2_tests/verify_header_test.go, consensus/tests/engine_v2_tests/vote_test.go, core/blockchain.go, eth/backend.go
When length of candidates is greater than `MaxMasternodes`, still store all of them in V2 snapshot. When calculating masternodes, truncate "candidates - penalty" to `MaxMasternodes`.
=> Extend masternode candidate

les/handler.go
cherry-picked from https://github.com/ethereum/go-ethereum/commit/a5237a27eaf81946a3edb4fafe13ed6359d119e4
=> fix-CVE-2018-12018

core/types/transaction.go, eth/api_tracer.go
This PR fix "nonce too low" error which is reported in #256 when calling below APIs:
- debug_traceBlockByNumber
- debug_traceBlockByHash
- debug_traceBlock 
The error is caused by function `ApplyEmptyTransaction` which does not increase nonce, such as:
```bash
curl -s -X POST -H "Content-Type: application/json" https://erpc.apothem.network/ -d '
{
"id": 6200,
"method": "eth_getBlockByNumber",
"params":["0x2e69c13", true]
}' | jq
```
```json
{
"result": {
"transactions": [
{
"from": "0xe65f06590ee4ed6d814309e5fa014b642b9272bd",
"nonce": "0x93fbe",
"to": "0x0000000000000000000000000000000000000092",
"transactionIndex": "0x0",
},
{
"from": "0xe65f06590ee4ed6d814309e5fa014b642b9272bd",
"nonce": "0x93fbe",
"to": "0x0000000000000000000000000000000000000089", …
```
=> fix "nonce too low" error when call debug_traceBlock api

cmd/XDC/bugcmd.go
The below error occurs when I run `make test` for current master branch:
```text
/usr/include/x86_64-linux-gnu/bits/stdio2.h:38:10: note: ‘__builtin___sprintf_chk’ output between 25 and 85 bytes into a destination of size 32
38 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
39 |                                   __glibc_objsize (__s), __fmt,
|                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
40 |                                   __va_arg_pack ());
|                                   ~~~~~~~~~~~~~~~~~
cmd/XDC/bugcmd.go:52:2: fmt.Fprintln arg list ends with redundant newline
FAIL	github.com/XinFinOrg/XDPoSChain/cmd/XDC [build failed]
?   	github.com/XinFinOrg/XDPoSChain/cmd/abigen	[no test …
```
=> cmd/XDC: remove redundant newline in bugcmd.go to pass make test

crypto/bn256/cloudflare/mul_arm64.h
ref: https://github.com/cloudflare/bn256/pull/4, https://github.com/ethereum/go-ethereum/pull/19183
fixes the below compile error on Mac ARM 
```
crypto/bn256/cloudflare/gfp_arm64.s:109: illegal or missing addressing mode for symbol R18
asm: assembly of crypto/bn256/cloudflare/gfp_arm64.s failed
```
=> mac arm build fix ref: https://github.com/cloudflare/bn256/pull/4, https://github.com/ethereum/go-ethereum/pull/19183

cicd/devnet/start.sh
Make Sync Mode Full to Avoid Race Condition.
The Fast Sync mode doesn't handle verify headers properly. It will download lots of headers but those headers doesn't save into disk yet. We need to fix it issue or Just use Sync Full mode to avoid this behaviour.
```
August 07, 2023 at 12:24 (UTC+4:00)	panic: runtime error: invalid memory address or nil pointer dereference	f6f05ff69071499fb74d3869b43dfce8	tfXdcNode
August 07, 2023 at 12:24 (UTC+4:00)	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6daffa]	f6f05ff69071499fb74d3869b43dfce8	tfXdcNode
August 07, 2023 at 12:24 (UTC+4:00)	goroutine 54169 [running]:	f6f05ff69071499fb74d3869b43dfce8	tfXdcNode
August 07, 2023 at 12:24 (UTC+4:00)	github.com/XinFinOrg/XDPoSChain/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0) …
```
=> make sync mode full to avoid race condition

core/database_util.go, eth/filters/api.go
Fix issue #208, make below JSONRPC metheds return right blockHash in logs:
- eth_getLogs
- eth_getFilterLogs
- eth_getFilterChanges
- eth_getTransactionReceipt
- [✅] External components
- [✅] Provide an end-to-end test plan in the PR description on how to manually test it on the devnet/testnet.
return wrong block hash: 0x194a513ea40c94fccaca470cccb24c2ff3bd6398dec9a04e3eb3a4bfef8a330e
```shell
curl -s -X POST https://erpc.apothem.network/ -H …
```
=> return right blockHash in logs

XDCxlending/lendingstate/common.go, XDCxlending/lendingstate/lendingitem.go, XDCxlending/order_processor.go, common/types.go, core/blockchain.go, core/lending_pool.go, core/state/statedb_utils.go, eth/hooks/engine_v1_hooks.go, internal/ethapi/api.go
The issue #280 reported a problem about `eth_getCandidateStatus`. I found some bugs about candidate functions during troubleshooting.
The function `GetPreviousCheckpointFromEpoch` returns wrong result when `epochNum == rpc.LatestEpochNumber` and blockNumer is 900\*N.
https://github.com/XinFinOrg/XDPoSChain/blob/master/internal/ethapi/api.go#L965-L984:
```go
func (s *PublicBlockChainAPI) GetPreviousCheckpointFromEpoch(ctx context.Context, epochNum rpc.EpochNumber) (rpc.BlockNumber, rpc.EpochNumber) {
var checkpointNumber uint64
epoch := s.b.ChainConfig().XDPoS.Epoch
if epochNum == rpc.LatestEpochNumber {
blockNumer := s.b.CurrentBlock().Number().Uint64()
diff := blockNumer % epoch
// checkpoint number
checkpointNumber = blockNumer - diff
epochNum = rpc.EpochNumber(checkpointNumber / epoch) …
```
=> fix candidates bugs in eth api

common/constants.go, common/constants/constants.go.testnet, params/version.go
In PR #291 the block number for testnet is not set. This PR:
- set the block number of new gas price to 63779191 for testnet 
- increases the block number of new gas price to 78383838 from 68383838 for mainnet
- bump the version to 1.4.9-beta2 from 1.4.9-beta
- [] Bugfix (non-breaking change which fixes an issue)
- [✅] Network
- [] External components
- [✅] This PR has sufficient test coverage (unit/integration test) OR I have …
=> set new gas price number for testnet and mainnet

cmd/puppeth/wizard_genesis.go, common/constants.go, common/constants/constants.go.testnet, consensus/XDPoS/XDPoS.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/tests/engine_v2_tests/initial_test.go, params/config.go
We have issue on test v2 on testnet which is setting up wrong switch number, this PR is for preventing same mistake on testnet and mainnet, to discover wrong number at boot stage.
=> check v2 switch block is epoch number

p2p/peer.go
cherry-picked from https://github.com/ethereum/go-ethereum/pull/27887
- [✅] Network
- [✅] Geth
=> fix-CVE-2023-40591

.travis.yml
This change only apply to devnet. We intend to improve the devnet deployment automation by running both old and new code at the same time to check the backwards compatibility.
=> Allow the devnet environment to auto deploy new and old code

internal/ethapi/api.go
This PR fixes the issue #326, make xdc blockchain supports the latest hardhat.
- [✅] Network
- [✅] Provide an end-to-end test plan in the PR description on how to manually test it on the devnet/testnet.
The issue #326 and [the post](https://www.xdc.dev/logeswaran/hardhat-upgradeable-proxy-support-for-xdc-bdp) reported that hardhat failed to deploy upgradeable contract to xdc blockchain. Below is the error message:
```text
yarn run …
```
=> EstimateGas support the latest hardhat

core/blockchain.go
fix a bug in func `procFutureBlocks`: the loop variable i is captured by func literal
```go
for i := range blocks {
_, err := bc.InsertChain(blocks[i : i+1])
// let consensus engine handle the last block (e.g. for voting)
if i == len(blocks)-1 && err == nil {
engine, ok := bc.Engine().(*XDPoS.XDPoS)
if ok {
go func() {
header := blocks[i].Header()
err = engine.HandleProposedBlock(bc, header)
if err != nil {
log.Info("[procFutureBlocks] handle proposed block has error", "err", err, "block hash", header.Hash(), "number", header.Number)
}
}()
}
}
}
```
_Put an `✅` in the boxes that …
=> Fix a loop closure bug in func  procFutureBlocks

core/lending_pool.go, core/order_pool.go, core/tx_pool.go
This PR fix the incorrect usages of `time.Since` with `defer`. The defered function arguments are evaluated immediately. We can wrap it into an anonymous function to delay their evaluation until the defer actually gets triggered.
Wrong:
```go
start := time.Now()
defer log.Debug("end promoteExecutables", "time", common.PrettyDuration(time.Since(start)))
```
Right:
```go
defer func(start time.Time) {
log.Debug("end promoteExecutables", "time", common.PrettyDuration(time.Since(start)))
}(time.Now())
```
- [✅] Not sure (Please specify below)
fix …
=> call to time.Since is not deferred

cmd/XDC/main.go, cmd/XDC/usage.go, cmd/utils/flags.go, node/config.go, node/defaults.go, node/node.go, rpc/http.go
This PR add a flag `rpc.writetimeout` with default value `10s` for RPC http server. With this flag, we can set the parameter `WriteTimeout` of RPC http server at the start time. It is very useful for debug API which need very long time to return result, such as #358.  
- [✅] Network
=> add flag rpcwritetimeout for rpc http server

eth/downloader/queue.go
This PR fix issue #264.
- [✅] Network
The issue #264 reported that our XDC private network halts after a few days, because some nodes stop producing blocks at random time. This problem occurs mostly in 2 weeks, minimum 2 days, maximum 3 months. I found the root cause after long time test and debug.
The function `syncWithPeer` in downloader posts `StartEvent` event at start time. and post `DoneEvent` or `FailedEvent` event at exit time. …
=> fix issue #264: private network halts randomly

consensus/XDPoS/api.go, consensus/tests/api_test.go
Adding the consensus configurations into the existing networkInformation api to help debug issues
- [✅ ] Regular KTLO or any of the maintaince work. e.g code style
- [ ✅] API
- [ ✅] This PR has sufficient test coverage (unit/integration test) OR I have provided reason in the PR description for not having test coverage
- [ ✅] Tested the backwards compatibility.
- [ ✅] Tested with XDC nodes running this version co-exist with those running the previous version.
=> Add config into network information API

consensus/XDPoS/XDPoS.go, consensus/XDPoS/api.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/XDPoS/engines/engine_v2/mining.go, consensus/XDPoS/engines/engine_v2/utils.go, consensus/XDPoS/utils/types.go, consensus/tests/api_test.go, consensus/tests/engine_v2_tests/api_test.go, consensus/tests/engine_v2_tests/helper.go, internal/web3ext/web3ext.go
**This PR is working in progress**
Adding a new API to help devs to debug when miners missed to produce block during their term (their round)
=> New api to list out missed rounds miners

core/blockchain.go
This PR fix a bug in function reportBlock as reported in [post](https://www.xdc.dev/sokiaoba/bad-block-error-in-testnet-after-upgrading-to-v1410-beta2-2gp6) and issue #369:
```text
Error: <nil>
```
The Error is always nil from EngineV2. This bug is caused by the function reportBlock:
```go
func (bc *BlockChain) reportBlock(block *types.Block, receipts types.Receipts, err error) {
bc.addBadBlock(block)
// V2 specific logs
config, _ := json.Marshal(bc.chainConfig)
var roundNumber = types.Round(0)
engine, ok := bc.Engine().(*XDPoS.XDPoS)
if ok {
roundNumber, err = engine.EngineV2.GetRoundNumber(block.Header())
}
var receiptString string
for _, receipt := range receipts {
receiptString += fmt.Sprintf("\t%v\n", receipt)
}
log.Error(fmt.Sprintf(`
########## BAD BLOCK #########
Chain config: %v …
```
=> Fix nil Error in function reportBlock

params/config.go
On devnet, 10 second timeout is too fast when there is heavy disk reading operation when receive/mine Epoch Block. Sometimes if disk performance is bad or no cache in the memory (reboot). Then it may occur timeout and round bump before sending Vote. 
On the other words: Block takes `x` second to be generated from miner and takes `y` second to consume to others. If `x + y > 10`, then timeout trigger, round++, then this block won't treat as valid.
```
WARN [01-16|07:09:22] Failed to pass the voting rule verification, blockRound is not equal currentRound x.currentRound=7954010 blockInfo.Round=7954009
```
_Put an `✅` in the boxes that …
=> fix timeout too fast issue

core/types/order_transaction.go, core/types/order_transaction_test.go
In the implementation, if from != acc and len(accTxs) == 1, the key from will be deleted from the map txs, and an empty array accTxs[1:] will be assigned to the key acc. As a result, when the for loop checks the key acc, a panic will occur with the error index out of range [0] with length 0 because the code is trying to get the value of accTxs[0].
=> XDP-02 fix Panic In ProcessOrderPending Leads To Chain Halt

crypto/bn256/bn256_fuzz.go, crypto/bn256/cloudflare/bn256.go, crypto/bn256/cloudflare/bn256_test.go, crypto/bn256/cloudflare/curve.go, crypto/bn256/cloudflare/gfp.go, crypto/bn256/cloudflare/gfp_amd64.s, crypto/bn256/cloudflare/mul_amd64.h, crypto/bn256/cloudflare/mul_bmi2_amd64.h, crypto/bn256/cloudflare/twist.go, crypto/secp256k1/curve.go
In go-ethereum, there is a list of edge cases or compilation-related issues fixed in the crypto module:
[crypto/secp256k1: add checking z sign in affineFromJacobian](https://github.com/ethereum/go-ethereum/pull/18419)
[crypto: added checks for nil pointers in Marshal functions](https://github.com/ethereum/go-ethereum/pull/19609)
[crypto/bn256: improve bn256 fuzzer](https://github.com/ethereum/go-ethereum/pull/21815)
[crypto/cloudflare/bn256: fix in-place addition and unmarshalling](https://github.com/ethereum/go-ethereum/pull/23419)
[crypto/bn256/cloudflare: fix asm for dynamic linking](https://github.com/ethereum/go-ethereum/pull/24476)
We fix these known issues to improve the robustness of the system.
_Put an `✅` in the …
=> XDC-01 | Potential Missed Fixings in `crypto` Module

rpc/client.go, rpc/client_test.go, rpc/http.go, rpc/server_test.go, rpc/testservice_test.go
Update rpc module to handle errors based on the eth PR: 
1. https://github.com/ethereum/go-ethereum/pull/26064/files
2. https://github.com/ethereum/go-ethereum/pull/26723/files
=> fix: update rpc module to include eth fix from #26064 and #26723

core/vm/privacy/ringct.go, core/vm/privacy/ringct_test.go
In the current function `PadTo32Bytes`:
```go
func PadTo32Bytes(in []byte) (out []byte) {
out = append(out, in...)
for {
if len(out) == 32 {
return
}
out = append([]byte{0}, out...)
}
}
```
- does not handle the length of parameter `in` greater than 32 bytes
- loop reduces the performance
=> fix bug and eliminate loop in func PadTo32Bytes

accounts/keystore/keystore.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/ethash/algorithm.go, core/bloombits/matcher.go
Replace all the time.after with time.newTimer to avoid memory leak
=> fix: replace all time.after with the time.newtimer

XDCxlending/lendingstate/lendingcontract.go, XDCxlending/lendingstate/lendingitem.go, core/lending_pool.go
Remove unused "false" return value from GetCollaterals
=> chore: remove the unused false return value from GetCollaterals method

core/vm/privacy/ringct.go, core/vm/privacy/ringct_test.go
[Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
](https://skyharbor.certik.com/report/e1b36ec7-b346-4ed9-a193-a72ad2337f68?findingIndex=1705333051226)
Malicious users can create signatures with invalid sizes but with forged numRing and ringSize to bypass the signature size check.
As a result, a panic from a buffer overflow may happen when the implementation tries to deserialize sig.S from the input with a big offset value.
=> RIN-02 Panic Due to Integer Overflow in Signature Size Calculation

accounts/abi/type.go
Fix issue in ABI where length is not checking after doing regex match
=> fix: missing length validaiton after doing regex

core/vm/privacy/bulletproof.go
Remove unnecessary int conversion in bulletproof.go
=> fix: remove unnecesasry int conversion in the bulletproof.go

accounts/abi/abi.go, accounts/abi/argument.go, accounts/abi/bind/base.go
Add two more if condition to double check the signature is valid in unpacklog method inside the abi
=> fix: missing validation in unpacklog

internal/ethapi/api.go
This PR improve the method eth_estimateGas:
-  return the right result for the tx which to is EOA and includes arbitrary data (fix issue #340)
- short circuit estimation and directly try 21000 if the tx is a plain value transfer
```bash
curl ${RPC} -X POST -H "Content-Type: application/json" -d '{
"id": 1234,
"method": "eth_estimateGas",
"params": [
{
"from": "0xD4CE02705041F04135f1949Bc835c1Fe0885513c",
"to": "0x85f33E1242d87a875301312BD4EbaEe8876517BA",
"data": "0x01234567"
}, …
```
=> improve the method eth_estimateGas

cicd/devnet/start.sh, cicd/mainnet/start.sh, cicd/testnet/start.sh
Change back to use PRIVATE_KEY as usually node owner put one private key and has their existed start script already.
=> Use PRIVATE_KEY env as start script

params/config.go
lint struct ChainConfig in file params/config.go
=> Lint struct ChainConfig in file params/config.go

common/constants.go, common/constants/constants.go.devnet, common/constants/constants.go.testnet, core/vm/eips.go, core/vm/evm.go, core/vm/interpreter.go, core/vm/jump_table.go, core/vm/opcodes.go, params/config.go
implement EIP-3198 make our chain support solidity v0.8.7 fully:
- set `BerlinBlock` and `LondonBlock` to block number `9999999999`
- implement opcode `BASEFEE`
- make `block.basefee` always return value `12500000000` in solidity
=> implement EIP-3198 and opcode BASEFEE

consensus/XDPoS/engines/engine_v1/engine.go
Fix a small bug where race condition could happen when concurrently update x.signer
=> fix: race condition of x.signer in v1 consensus

common/constants.go, common/constants/constants.go.devnet, common/constants/constants.go.testnet, core/evm.go, core/vm/evm.go, core/vm/instructions.go, core/vm/instructions_test.go, core/vm/interpreter.go, core/vm/jump_table.go, core/vm/opcodes.go, params/config.go
Implement EIP-4399, PRERANDAO opcode.
The random value is calculated from block number through keccak hash.
1. Modify common/constants.go `MergeBlock=0` to make this EIP work immediately.
2. Write a contract to print PRERANDAO (0x44). Deploy it.
3. Send tx to the contract in different block numbers. Check the result equals hash of the block number.
=> implement EIP-4399, PREVRANDAO opcode

consensus/XDPoS/engines/engine_v2/timeout.go
Fix the issue in new consensus error handling during timeout where lock not applied for multiple go routine execution
=> fix: add lock for haserror variable in timeout.go

rpc/http.go
The PR #363 only add parameter `WriteTimeout` for http server. But there are potential issues when timeout:
- the connection is closed and server return empty reply
- the request Context is not canceled
This PR set `http.TimeoutHandler` for http server in package rpc when timeout:
- return with http code 503 and static body message: `{"error":"http server timeout"}`
- the request Context is canceled
background information:
- https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
- https://blog.dharnitski.com/2021/03/14/timeout-vs-handler/
- https://www.sobyte.net/post/2022-01/go-http-server-timeout/
- https://taoshu.in/go/go-http-server-timeout.html
Which part of the …
=> add http.TimeoutHandler for rpc http server

core/state/state_object.go, core/state/statedb.go, internal/ethapi/api.go, internal/jsre/deps/web3.js
Add method `eth_getAccountInfo` which returns below properties for an account:
- address
- balance
- code hash
- for contract: Keccak256(code)
- for exist EOA: Keccak256(nil) = `0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`
- for inexistent account: `0x0000000000000000000000000000000000000000000000000000000000000000`
- code size
- nonce
- storage hash
**request**
```bash
curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
"id": 8001,
"method": "eth_getAccountInfo",
"params": [
"0x0000000000000000000000000000000000000088",
"latest"
]
}' | jq
```
**response**
```json
{
"id": 8001,
"result": {
"address": "0x0000000000000000000000000000000000000088",
"balance": "0x1fc3842bd1f071c00000",
"codeHash": …
```
=> add method `eth_getAccountInfo`

common/constants.go, common/constants/constants.go.devnet, common/constants/constants.go.testnet, core/asm/asm_test.go, core/vm/eips.go, core/vm/interpreter.go, core/vm/jump_table.go, core/vm/opcodes.go, params/config.go
Implement EIP-3855: PUSH0 instruction. With constant ShanghaiBlock.
1. Modify common/constants.go set ShanghaiBlock to a small constant, to make this EIP work quickly.
2. Write a contract to run PUSH0 (0x5f). Deploy it.
3. Send tx to the contract in different block numbers. Check the result after EIP works. Also check the result before EIP works.
=> core/vm: implement EIP-3855: PUSH0 instruction.

common/lru/basiclru.go, common/lru/basiclru_test.go, common/lru/blob_lru.go, common/lru/blob_lru_test.go, common/lru/lru.go
This package is picked from [ethereum PR #26162](https://github.com/ethereum/go-ethereum/pull/26162) and will be used in later.
Method names are the same as github.com/hashicorp/golang-lru and the new type can be used as a drop-in replacement.
Two reasons to do this:
- It's much easier to understand what a cache is for when the types are right there.
- Performance: the new implementation performs zero memory allocations in aAdd when the cache is at capacity. 
=> common/lru: add generic LRU implementation

cmd/XDC/chaincmd.go
Before exiting the XDC application using command lines, close the database to prevent any potential storage collisions.
This change is advised by the auditing team.
ref previous PR which was closed to combine changes into 1 commit:  https://github.com/XinFinOrg/XDPoSChain/pull/476
CMD
=> Ensure DB is close before client exit

core/types/consensus_v2.go
There are several structs passed into json.Marshal without json tags. It may bring unexpected errors when renaming fields. 
This change is advised by the auditing team.
=> Missing `json` Field Tags in Marshalled Struct

consensus/XDPoS/engines/engine_v1/engine.go
Following up on this comment https://github.com/XinFinOrg/XDPoSChain/pull/445/files#r1510519857 to use rlock instead of the lock for better performance
=> use rlock instead of lock in v1 consensus engine

core/state/statedb.go, core/state/statedb_test.go
The StateDB type utilizes a dbErr to track database errors. It is employed by both the consensus core and the VM which are not designed to manage such errors directly.
Errors encountered during database operations are recorded in dbErr using the SetError function. During a Commit, functions like deleteStateObject, updateStateObject, and getStateObject are called based on the current state of stateObject to manage trie node data for deletion, update, or retrieval. If a data node is missing, dbErr is set accordingly.
To avoid committing  erroneous state, check the dbErr before performing Commit action.
This issue is raised by the auditing team
ref: https://github.com/ethereum/go-ethereum/pull/21039/files
_Put an `✅` in the boxes …
=> check potential error before Commit

core/blockchain.go, core/headerchain.go, eth/api_backend.go, internal/ethapi/api.go, internal/ethapi/backend.go, les/api_backend.go, light/lightchain.go
This PR support for EIP-1898.
```bash
MY_ADDRESS="0xD4CE02705041F04135f1949Bc835c1Fe0885513c"
XDCValidator="0x0000000000000000000000000000000000000088"
HASH0=$(curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
"id": 4003,
"method": "eth_getBlockByNumber",
"params": [
"0x0",
false
]
}' | jq -r '.result.hash')
HASH1=$(curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
"id": 4003,
"method": "eth_getBlockByNumber",
"params": [
"0x1", …
```
=> implement EIP-1898

core/state/statedb.go, core/state/statedb_test.go
This reverts commit [0114ecabd06e4cdadf8a084f5932635d0b631166](https://github.com/XinFinOrg/XDPoSChain/pull/484) due to it causing unexpected issues. 
statedb
=> Revert "core/state: abort commit if errors have occurred (#484)"

accounts/abi/bind/backends/simulated.go, eth/filters/api.go, eth/filters/filter.go, eth/filters/filter_system_test.go, interfaces.go
This PR fix #457 by support parameter `blockHash` in the input of method `eth_getLogs`.
**Notice: this function is removed by PR #131.**
---
**request:**
```bash
curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
"id": 6003,
"method": "eth_getLogs",
"params": [
{
"blockHash": "'"${HASH}"'"
}
]
}' | jq
```
**response:**
```json
{
"id": 6003,
"result": [
{
"address": "0x0000000000000000000000000000000000000089",
"topics": [ …
```
=> implement EIP-234: add blockHash param for eth_getLogs

eth/bloombits.go
Related to https://github.com/XinFinOrg/XDPoSChain/pull/400
After we use time.Ticker it didn't allow to have 0 time duration. When we call eth_getLogs it panics and crash the nodes, change to non 0 will resolve this issue
Thanks @gzliudan for finding the root cause.
Error Log:
Too complicate to write unit test, will do the test on devnet while calling eth_getLogs api.
=> after we use time.Ticker it didn't allow to have 0 time duration

miner/worker.go
remove 1s waiting time in miner, which is unnecessary.
**Test plan:** deploy a master node in devnet and check if it mines blocks.
=> XDC-05 remove 1s waiting time in miner

accounts/abi/bind/backends/simulated.go, eth/filters/api.go, eth/filters/bench_test.go, eth/filters/filter.go, eth/filters/filter_system.go, eth/filters/filter_test.go, event/event.go
picked some PRs about package filter from ethereum:
[2018-05-09 PR #16682](https://github.com/ethereum/go-ethereum/pull/16682): eth/filter: check nil pointer when unsubscribe
[2018-06-14 PR #16920](https://github.com/ethereum/go-ethereum/pull/16920): eth/filters: make filterLogs func more readable
[2018-07-12 PR #16734](https://github.com/ethereum/go-ethereum/pull/16734): accounts, eth, les: blockhash based filtering on all code paths
[2018-07-24 PR #17234](https://github.com/ethereum/go-ethereum/pull/17234): eth/filters: improve error message for invalid filter topics
[2018-07-30 PR #17267](https://github.com/ethereum/go-ethereum/pull/17267): all: simplify switches
[2018-07-31 PR #17284](https://github.com/ethereum/go-ethereum/pull/17284): eth/filters: fix the block range assignment for …
=> improve package eth/filter

.github/workflows/ci.yml, cicd/devnet/terraform/.env, cicd/devnet/terraform/main.tf, cicd/devnet/terraform/module/region/ecs.tf, cicd/devnet/terraform/module/region/variables.tf, cicd/devnet/terraform/s3.tf, cicd/devnet/terraform/variables.tf, cicd/terraform/main.tf, cicd/terraform/s3.tf, cicd/terraform/variables.tf
* Refactor RPC node and move devnet rpc node to same place as testnet and devnet
* Change S3 bucket location to be more general
=> Ci improvement

consensus/clique/clique.go, consensus/misc/gaslimit.go, params/protocol_params.go
Add checks to make sure gasLimit is within valid range as advised by the auditing team.
ref: https://github.com/ethereum/go-ethereum/pull/22836
=> consensus/clique: add some missing checks (#22836)

core/state/statedb.go
The statedb.go Copy was copying references for self.logs which is []*type.Log. The DeepCopy will create new instance of Log objects so now the copy is independent from the original.
StateDB
=> add log deepcopy

consensus/XDPoS/XDPoS.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/XDPoS/engines/engine_v2/epochSwitch.go, consensus/XDPoS/engines/engine_v2/snapshot.go, consensus/XDPoS/engines/engine_v2/snapshot_test.go, consensus/XDPoS/engines/engine_v2/timeout.go, consensus/XDPoS/engines/engine_v2/utils.go, consensus/tests/engine_v2_tests/mine_test.go, consensus/tests/engine_v2_tests/verify_header_test.go
Rename snapshot property name NextEpochCandidates to make more correct meanings, the final masternodes list is calculated at epoch switch block.
=> PPX-01 rename NextEpochMasterNodes to NextEpochCandidates

consensus/XDPoS/engines/engine_v2/vote.go
PPX-01 add verification of vote signer belonging to masternodes.
=> PPX-01 add verification of vote signer belonging to masternodes

core/blockchain.go
fix: Future Blocks Are Always Verified Instead Of Queued.
=> XDF-05 fix: Future Blocks Are Always Verified Instead Of Queued

internal/ethapi/api.go
This PR refactor functions about eth_call and eth_estimateGas:
1. change `func (s *PublicBlockChainAPI) doCall` to `func DoCall`.
2. change `func (s *PublicBlockChainAPI) doEstimateGas` to `func DoEstimateGas`.
3. change ` b.BlockByNumber(ctx, rpc.LatestBlockNumber)` to `b.BlockByNumberOrHash(ctx, blockNrOrHash)` in function DoEstimateGas to support all blocks.
=> rename function doCall and doEstimateGas

consensus/XDPoS/engines/engine_v2/snapshot.go
Revert rename a json field as it creates a hardfork from db, it can't read from existed db record.
introduced by this PR: https://github.com/XinFinOrg/XDPoSChain/pull/510
=> revert rename change as change db field name and stops block chain

cicd/devnet/start.sh, cicd/mainnet/start.sh, cicd/testnet/start.sh, cmd/XDC/config.go, cmd/XDC/consolecmd_test.go, cmd/XDC/main.go, cmd/utils/flags.go, common/constants.go, common/constants/constants.go.devnet, common/constants/constants.go.testnet
As agreed by the developer community to enable 0x prefix as default going forward. This will make sure we have less friction with new partners at later date.
=> use 0x address scheme by default and add new enable xdc prefix flag

core/blockchain.go, core/database_util.go, core/state/statedb.go, core/state_processor.go, core/types/gen_receipt_json.go, core/types/gen_tx_json.go, core/types/receipt.go, miner/worker.go
Apply [PR #17662](https://github.com/ethereum/go-ethereum/pull/17662) which add files:
- BlockHash
- BlockNumber
- TransactionIndex
for struct `Receipt`.
=> types, core, miner: add block location fields to receipt

core/vm/contracts.go, core/vm/contracts_test.go, core/vm/evm.go, params/config.go
This change is a part of disabling XDCx, removing precompile contracts addresses after the switch block.
=> add trigger for disable XDCx precompiles

core/state/state_object.go, core/state/statedb.go, internal/ethapi/api.go
Extend eth_call and estimateGas api with state override
I already tested with a local xdc node. And we can also do the same test on devnet/testnet. The plan is as follows.
```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" \
--data '{"method":"eth_call","params":[{"to":"0x0000000000000000000000000000000000000088","data":"0xef18374a"}, "latest"],"id":1,"jsonrpc":"2.0"}'
```
Expected result : the number of owner
this fake code should return 0xff: `60ff60005360016000f3`, no …
=> extend eth_call and estimateGas api with state override

ethclient/ethclient.go, internal/ethapi/api.go, internal/web3ext/web3ext.go
- This pull request implement the `eth_getBlockReceipts` method. 
-  this PR depends on after EIP-1559
- [✅ ] New feature (non-breaking change which adds functionality)
- [ ✅] Geth
- [✅ ] N/A
=> Add method: eth_getBlockReceipts

eth/downloader/downloader_test.go, eth/downloader/queue.go
This PR:
- fixes issue #377 
- pick PR #20690 from geth
=> fix issue #377 and a bug in queue

consensus/XDPoS/engines/engine_v1/engine.go
This PR fix v2.0.0 sync problem for mainet by revert commit #531. When we sync mainnet with [old v2.0.0](https://github.com/XinFinOrg/XDPoSChain/commit/3ae6f752bda4865664fdb3914b2a119eaaee1ffb), each block reported `Reorg` and `Chain split detected` WARN messages after catch up the latest height, such as:
```text
INFO [07-18|11:02:55] Imported new chain segment               blocks=1 txs=4   mgas=0.414   elapsed=35.412ms  mgasps=11.691  number=77335639 hash=88c610…c7db38 cache=0.00B
INFO [07-18|11:02:56] Imported new chain segment               blocks=1 txs=4   mgas=0.414   elapsed=26.552ms  mgasps=15.592  number=77335639 hash=790a6f…f48b2f cache=0.00B
WARN [07-18|11:02:57] Reorg                                    oldBlock hash=0x88c610f8f05ae42d34eea4a8f60260658a6373c02686de4862e5688cd7c7 …
```
=> fix v2.0.0 sync problem for mainnet

internal/ethapi/api.go, params/config.go
In the function `DoCall`
Old code:
```go
block, err := b.BlockByHash(ctx, header.Hash())
```
New code:
```go
block, err := b.BlockByNumberOrHash(ctx, blockNrOrHash)
```
The function `BlockByHash` returns nil block during reorg, but `BlockByNumberOrHash` returns block which is we want.
In the function `func (c *ChainConfig) Rules(num *big.Int)`:
Old code:
```go
IsXDCxDisable:    c.IsTIPXDCXReceiver(num),
```
`IsTIPXDCXReceiver` means `common.TIPXDCX <= num < common.TIPXDCXReceiverDisable`.
New code:
```go
IsXDCxDisable:    c.IsXDCxDisable(num),
```
`IsXDCxDisable` means `num >= common.TIPXDCXReceiverDisable`.
_Put an `✅` in the boxes …
=> Fix crash during reorg for v2.0.0

params/config.go
Matching the current round number from the block, not the timeout round number, timeout round number will be delete after all the nodes gets reverted.
=> lower the devnet cert to recover devnet again

internal/ethapi/api.go
The value of timeout for a single call is 5 seconds now.
```go
func (s *PublicBlockChainAPI) Call(ctx context.Context, args CallArgs, blockNrOrHash *rpc.BlockNumberOrHash, overrides *StateOverride) (hexutil.Bytes, error) {
// ......
result, _, failed, err, vmErr := DoCall(ctx, s.b, args, *blockNrOrHash, overrides, vm.Config{}, 5*time.Second, s.b.RPCGasCap())
if err != nil {
return nil, err
}
// ......
}
```
When the system is extremely slow, such as the CPU is exhausted, the function `Call` will return `err="execution aborted (timeout = 5s)"`. This is OK for normal transactions. But when we call the function `UpdateM1`:
```go
// in function WriteBlockWithState
err := bc.UpdateM1()
if err != nil {
log.Crit("Error when update masternodes set. Stopping node", "err", err, "blockNum", …
```
=> make eth_call not timeout during UpdateM1

internal/ethapi/api.go
The value of timeout for a single call is 5 seconds now.
```go
func (s *PublicBlockChainAPI) Call(ctx context.Context, args CallArgs, blockNrOrHash *rpc.BlockNumberOrHash, overrides *StateOverride) (hexutil.Bytes, error) {
// ......
result, _, failed, err, vmErr := DoCall(ctx, s.b, args, *blockNrOrHash, overrides, vm.Config{}, 5*time.Second, s.b.RPCGasCap())
if err != nil {
return nil, err
}
// ......
}
```
When the system is extremely slow, such as the CPU is exhausted, the function `Call` will return `err="execution aborted (timeout = 5s)"`. This is OK for normal transactions. But when we call the function `UpdateM1`:
```go
// in function WriteBlockWithState
err := bc.UpdateM1()
if err != nil {
log.Crit("Error when update masternodes set. Stopping node", "err", err, "blockNum", …
```
=> make MasternodeVotingSMC tx never timeout

core/blockchain.go, eth/api_backend.go, eth/api_tracer.go, eth/backend.go, eth/hooks/engine_v1_hooks.go, internal/ethapi/api.go
This PR fixes some panic caused by nil block, header, statedb, such as #271.
=> Fix some panic cuased by nil block, statedb, header

core/blockchain.go
fix https://github.com/XinFinOrg/XDPoSChain/pull/583#discussion_r1706331377
=> Fix writeblock

cmd/XDC/main.go, common/constants/constants.go.testnet, consensus/XDPoS/engines/engine_v1/engine.go, eth/backend.go
Remove Legacy Masternode validate logic on testnet. Bug comes from this PR https://github.com/XinFinOrg/XinFin-Node/pull/137.
=> remove legacy testnet validate masternode logic

cicd/terraform/main.tf
remove ecs rpc as we migrate to ec2 ones
=> remove ecs rpc node as we have ec2 ones

core/rawdb/accessors_chain.go, miner/worker.go
- reorder the function sequence in package `rawdb`
- fix a bug in #583: `snapshotBlock` and `snapshotReceipts` are never updated
- optimize the functions: `updateSnapshot`, `pending`, `pendingBlock`
**Reference:**
#15853
#16497
#19734
#23033
#23178
#23256
=> fix a bug in PR #583: snapshot is not updated 

core/types/transaction.go, eth/api_tracer.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go
A user reported a bug in [here](https://www.xdc.dev/steven_lin_1581b1cdfd98a6/wip-ethestimategas-rpc-method-on-apothem-with-erc20-transfer-always-return-execution-reverted-error-5fgl) when using the Go-Ethereum client to call JSON-RPC. The issue arises because the parameter field 'data' has been renamed to 'input' from version 1.13 onwards.
This PR adds support of "input" field in `eth_call`,`eth_estimateGas` . Field "data" will be still supported
When this PR is not merged:
- For RPC="http://127.0.0.1:8545", the changes from this PR are applied.
- For RPC="https://arpc.apothem.network/", the changes from this PR are not applied.
- `data` field
Request:
```shell
RPC="http://127.0.0.1:8545"
curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
"id": 8001, …
```
=> support both input and data in eth_call, eth_estimateGas, personal_sendTransaction

core/tx_list.go, core/tx_pool.go, core/tx_pool_test.go
This PR fixes several race conditions in the txpool:
- A race between txlist.Removed() and txlist.Reheap() on who is allowed to reheap the list
- A race between several methods in txList on updating the txlist.stales counter
- A race during testing between the txpool.loop() and reseting the txpool's blockchain between tests
- A race during testing when updating txpool.chain.gaslimit from within a test
Reference: #23474
=> fix race conditions in txpool

go.mod, go.sum
This PR update [fastcache](https://github.com/VictoriaMetrics/fastcache) to the latest version v1.12.2. The current version in our go.mod is v1.21.1. Here is the change log since v1.12.1:
```text
c5013df1 2023-11-24 13:25:57: go.mod: update dependencies with `go get -u ./... && go mod tidy && go mod vendor`
959e53c7 2023-11-24 13:23:24: fastcache.go: re-create the bucket.m map inside cleanLocked() in order to reduce map fragmentation
```
According to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5379, the commit 959e53c7 will help reducing memory usage and GC pressure for long-running processes.
_Put an `✅` in the boxes that …
=> update fastcache to v1.12.2

core/error.go, core/state_transition.go, core/vm/errors.go, core/vm/evm.go
This PR implements EIP-2681.
Reference: #23853
=> implement EIP-2681

cmd/gc/main.go, common/lru/basiclru.go, core/blockchain.go, core/blockchain_test.go, core/headerchain.go, core/state/database.go
This PR:
- update package `common/lru`: #29348 and #29399
- implement generic LRU for core and cmd: #26162
=> update package common/lru and implement generic LRU

core/vm/errors.go, core/vm/evm.go
This PR implement [EIP-3541](https://eips.ethereum.org/EIPS/eip-3541) which reject new contract code starting with the 0xEF byte.
Reference: #22809
=> implement EIP-3541

event/feed.go, event/feed_test.go
This PR include below PRs from geth to fixes some issues in event package:
- #16680
- #20324
- #20653 
- #27249
=> add missing unlock before panic in package event

consensus/XDPoS/XDPoS.go, consensus/XDPoS/api.go, consensus/XDPoS/engines/engine_v2/epochSwitch.go, consensus/tests/engine_v2_tests/api_test.go, internal/web3ext/web3ext.go
GetEpochNumbersBetween API.
Give two numbers, begin and end number. Return all epoch block numbers in between.
=> feat: GetEpochNumbersBetween API

params/config.go
The progress is stuck at block number 65533267 when we sync testnet. And the below error appears again and again:
```text
ERROR[09-03|11:12:55]
########## BAD BLOCK #########
Chain config: {"chainId":51,"homesteadBlock":1,"eip150Block":2,"eip150Hash":"0x0000000000000000000000000000000000000000000000000000000000000000","eip155Block":3,"eip158Block":3,"byzantiumBlock":4,"XDPoS":{"period":2,"epoch":900,"reward":5000,"rewardCheckpoint":900,"gap":450,"foudat
ionWalletAddr":"0x746249c61f5832c5eed53172776b460491bdcd5c","SkipV1Validation":false,"v2":{"switchBlock":56828700,"config":{"maxMasternodes":15,"switchRound":0,"minePeriod":2,"timeoutSyncThreshold":3,"timeoutPeriod":20,"certificateThreshold":0.45},"allConfigs":{"0":{"maxMasternodes …
```
=> fix sync issue for testnet

core/vm/gen_structlog.go
This PR use `gencodec` to create file `gen_structlog.go`.
```bash
go install github.com/fjl/gencodec@latest
cd XDPoSChain/core/vm
gencodec -type StructLog -field-override structLogMarshaling -out gen_structlog.go
```
Reference: #21715
=> core/vm: marshall returnData as hexstring in trace logs

accounts/abi/bind/backends/simulated.go, core/evm.go, core/state_processor.go, core/state_transition.go, core/token_validator.go, core/vm/contracts_test.go, core/vm/evm.go, core/vm/gas_table_test.go, core/vm/instructions.go, core/vm/instructions_test.go, core/vm/logger_test.go, core/vm/runtime/env.go, eth/api_backend.go, eth/api_tracer.go, eth/tracers/testing/calltrace_test.go, eth/tracers/tracer.go, eth/tracers/tracer_test.go, eth/tracers/tracers_test.go, les/api_backend.go, les/odr_test.go, light/odr_test.go, tests/state_test_util.go, tests/vm_test_util.go
This PR splits vm.Context into BlockContext and TxContext.
Refreence: #21672
=> split vm.Context into BlockContext and TxContext

core/vm/evm.go
This PR replaces function `precompile2` with `precompile`:
```go
func (evm *EVM) precompile(addr common.Address) (PrecompiledContract, bool) {
var precompiles map[common.Address]PrecompiledContract
switch {
case evm.chainRules.IsXDCxDisable:
precompiles = PrecompiledContractsXDCv2
case evm.chainRules.IsIstanbul:
precompiles = PrecompiledContractsIstanbul
case evm.chainRules.IsByzantium:
precompiles = PrecompiledContractsByzantium
default:
precompiles = PrecompiledContractsHomestead
}
p, ok := precompiles[addr]
return p, ok
}
func (evm *EVM) precompile2(addr common.Address) (PrecompiledContract, bool) {
var precompiles map[common.Address]PrecompiledContract
switch {
case evm.chainRules.IsXDCxDisable:
precompiles = PrecompiledContractsXDCv2
case evm.chainRules.IsIstanbul && …
```
=> core/vm: replace function `precompile2` with `precompile`

core/vm/contracts.go, core/vm/contracts_test.go, core/vm/evm.go, core/vm/gas_table.go, core/vm/instructions.go, core/vm/interpreter.go, core/vm/operations_acl.go, core/vm/runtime/runtime.go, core/vm/stack.go, trie/secure_trie.go
Apply below PRs for package `core/vm` from geth:
- #21222
- #21903
=> core/vm: less allocations and redundant conversions

accounts/abi/bind/auth.go, core/rawdb/accessors_chain_test.go, crypto/crypto.go, crypto/crypto_test.go, eth/tracers/internal/tracers/assets.go, eth/tracers/testing/calltrace_test.go
The `ioutil` package has been deprecated as of Go 1.16, and its functionality has been merged into the `io` and `os` packages.
=> all: replace uses of ioutil with io and os

eth/bft/bft_handler.go, params/version.go
continue relocate to address #655 issue
=> relocate broadcast logic

cmd/XDC/main.go, cmd/XDC/usage.go, cmd/utils/flags.go, eth/ethconfig/config.go, eth/peer.go
This PR:
- increase default value of `RPCGasCap` from `25000000` to `50000000`
- add flag `rpc-gascap` to set `RPCGasCap` when startup node
Reference:
- #19401
- #23028
- [✅] Geth
- [✅] Tested with XDC nodes running this version co-exist with those running the previous version.
=> add flag rpc-gascap and set RPCGasCap to 50M

core/database_util.go
This PR fixes issue #650 by set right blockHash in the result of eth_getLogs.
=> return right blockHash for eth_getLogs (#650)

cmd/evm/runner.go, consensus/misc/forks.go, core/asm/asm.go, core/blockchain.go, core/types/transaction.go, core/vm/instructions_test.go, core/vm/logger.go, core/vm/runtime/runtime_test.go, eth/api_test.go, eth/filters/api_test.go, internal/ethapi/api.go, mobile/types.go, p2p/discover/database_test.go, p2p/discv5/database_test.go, rlp/rlpgen/gen.go, test.txt, tests/state_test.go, trie/trie_test.go
This PR changes format:
- `0x%x` to `%#x`
- `0x%X` to `%#X`
Reference: #25221
=> all: change format 0x%x to %#x

core/vm/analysis.go, core/vm/contracts.go, core/vm/contracts_test.go, core/vm/instructions.go, core/vm/instructions_test.go, core/vm/interface.go, core/vm/interpreter.go, core/vm/jump_table.go, core/vm/jump_table_test.go, core/vm/runtime/runtime_test.go
pick the following PRs from geth:
- #24048
- moves the dynamic memory check function to only be checked if the op has a dynamic gas function. 
- skip two conditionals on the cheap ops.
- set cost earlier, making errors more correct than previously
- #24714
- #24845
- #24867
- #24860
- #23500
- #24783
- #25183
- #25880
- #26137
=> upgrade package core/vm

p2p/simulations/http.go, rpc/client.go, rpc/http.go, rpc/http_test.go, rpc/json.go, rpc/server.go, rpc/server_test.go, rpc/testservice_test.go, rpc/types.go, rpc/websocket.go, rpc/websocket_test.go
This PR fixes the staticcheck warning [SA1029: Inappropriate key in call to context.WithValue](https://staticcheck.dev/docs/checks/#SA1029) by:
- add PeerInfo in package rpc: #24255
- ignore SA1029 in file p2p/simulations/http.go since it will be removed later: #30250
The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions between packages using context. Users of WithValue should define their own types for keys.
To avoid allocating when assigning to an interface{}, context keys often have concrete type struct{}. Alternatively, exported context key variables’ static type should be a pointer or interface.
Which part of the codebase …
=> fix staticcheck warning SA1029: inappropriate key in call to context.WithValue

accounts/abi/bind/bind_test.go, cmd/puppeth/module_explorer.go, cmd/puppeth/module_wallet.go, p2p/discv5/net.go, p2p/discv5/ntp.go, whisper/mailserver/mailserver.go
This PR fixes staticcheck warning [S1039: unnecessary use of fmt.Sprintf](https://staticcheck.dev/docs/checks#S1039):
Calling fmt.Sprint with a single string argument is unnecessary and identical to using the string directly.
=> all: fix staticcheck warning S1039: unnecessary use of fmt.Sprintf

contracts/trc21issuer/trc21issuer_test.go, internal/ethapi/api.go
This PR fixes the staticcheck warning [SA1012: pass nil context.Context to a function](https://staticcheck.dev/docs/checks#SA1012):
A nil context.Context is being passed to a function, consider using context.TODO instead
=> fix staticcheck warning SA1012: pass nil Context to function

accounts/abi/bind/backends/simulated.go, consensus/XDPoS/engines/engine_v2/forensics_test.go, consensus/tests/engine_v2_tests/helper.go, metrics/json_test.go
This PR fixes the staticcheck warning [SA1006: Printf with dynamic first argument and no further arguments](https://staticcheck.dev/docs/checks#SA1006):
Using fmt.Printf with a dynamic first argument can lead to unexpected output. The first argument is a format string, where certain character combinations have special meaning. If, for example, a user were to enter a string such as
```text
Interest rate: 5%
```
and you printed it with
```go
fmt.Printf(s)
```
it would lead to the following output:
```text
Interest rate: 5%!(NOVERB).
```
Similarly, forming the first parameter via string concatenation with user input should be avoided for the same reason. When printing user input, either use a variant of fmt.Print, or use the %s Printf verb and pass the string as an argument.
What types of …
=> all: fix staticcheck warning SA1006

consensus/tests/engine_v1_tests/helper.go, consensus/tests/engine_v2_tests/helper.go, contracts/utils.go, eth/api_backend.go
This PR fixes the staticcheck warning [ST1019](https://staticcheck.dev/docs/checks#ST1019):
importing the same package multiple times
=> all: fix staticcheck warning ST1019: import package twice

XDCxlending/lendingstate/lendingitem.go, core/lending_pool.go
This PR fixes the staticcheck warning [S1002: omit comparison to bool constant](https://staticcheck.dev/docs/checks#S1002):
Before:
```go
if x == true {}
```
After:
```
if x {}
```
=> core, XDCxlending/lendingstate: fix staticcheck warning S1002: omit comparison to bool constant

ethclient/ethclient.go, interfaces.go
This PR fixes the staticcheck warning [ST1012: poorly chosen name for error variable](https://staticcheck.dev/docs/checks#ST1012):
Error variables that are part of an API should be called `errFoo` or `ErrFoo`.
=> XDPoSChain, ethclient: fix staticcheck warning ST1012: rename NotFound to ErrNotFound

crypto/bn256/cloudflare/gfp_decl.go
This PR fixes the staticcheck warning [SA9009: ineffectual compiler directive](https://staticcheck.dev/docs/checks#SA9009):
A potential Go compiler directive was found, but is ineffectual as it begins with whitespace.
crypto/bn256/cloudflare/gfp_decl.go:15:1: ineffectual compiler directive due to extraneous space: "// go:noescape" (SA9009)
=> crypto/bn256: fix staticcheck warning SA9009: ineffectual go compiler directive

core/state_processor.go
This PR fixes the staticcheck warning [SA6005: should use strings.EqualFold](https://staticcheck.dev/docs/checks#SA6005):
Converting two strings to the same case and comparing them like so
```go
if strings.ToLower(s1) == strings.ToLower(s2) {
...
}
```
is significantly more expensive than comparing them with `strings.EqualFold(s1, s2)`. This is due to memory usage as well as computational complexity.
`strings.ToLower` will have to allocate memory for the new strings, as well as convert both strings fully, even if they differ on the very first byte. `strings.EqualFold`, on the other hand, compares the strings one character at a time. It doesn’t need to create two intermediate strings and can return as soon as the first non-matching character has been found.
For a more in-depth explanation …
=> core: fix staticcheck warning SA6005: should use strings.EqualFold

XDCxDAO/mongodb.go
This PR fixes the  staticcheck warning [SA5007: infinite recursive call](https://staticcheck.dev/docs/checks#SA5007):
A function that calls itself recursively needs to have an exit condition. Otherwise it will recurse forever, until the system runs out of memory.
This issue can be caused by simple bugs such as forgetting to add an exit condition. It can also happen “on purpose”. Some languages have tail call optimization which makes certain infinite recursive calls safe to use. Go, however, does not implement TCO, and as such a loop should be used instead.
_Put an `✅` in the boxes once you have …
=>  XDCxDAO: fix staticcheck warning SA5007: infinite recursive call

accounts/abi/bind/base.go, cmd/gc/main.go, cmd/puppeth/wizard_netstats.go, consensus/XDPoS/engines/engine_v1/engine.go, consensus/XDPoS/engines/engine_v2/forensics.go, consensus/clique/clique.go, core/blockchain.go, core/order_pool_test.go, eth/handler.go, les/backend.go, les/odr_requests.go, les/peer.go, les/randselect.go, les/retrieve.go, light/postprocess.go, mobile/ethereum.go, p2p/discv5/ticket.go, trie/trie.go, whisper/whisperv6/whisper.go
This PR fixes the nil issues reported by from nilness and staticcheck.
- issues from staticcheck
```text
cmd/puppeth/wizard_netstats.go:85:20: possible nil pointer dereference (SA5011)
cmd/puppeth/wizard_netstats.go:88:5: this check suggests that the pointer can be nil
mobile/ethereum.go:71:24: possible nil pointer dereference (SA5011)
mobile/ethereum.go:68:5: this check suggests that the pointer can be nil
```
- issues from nilness
```text
consensus/XDPoS/engines/engine_v2/forensics.go:212:125: nil dereference in field selection
light/postprocess.go:167:8: panic with nil value
les/backend.go:150:8: panic with nil value
les/odr_requests.go:199:8: panic with nil value
les/odr_requests.go:359:8: panic with nil value
les/peer.go:282:8: panic with nil value
les/peer.go:304:8: panic with nil …
```
=> fix nil issues reported by nilness and staticcheck

XDCxlending/XDCxlending.go, XDCxlending/order_processor.go, consensus/XDPoS/engines/engine_v1/engine.go, contracts/utils.go, eth/api_backend.go, eth/hooks/engine_v1_hooks.go, eth/hooks/engine_v2_hooks.go, miner/worker.go
This PR fixes the staticcheck warning [ST1008](https://staticcheck.dev/docs/checks#ST1008):
A function’s error value should be its last return value
=> all: fix staticcheck warning ST1008: error should be last return value

XDCxlending/lendingstate/statedb_test.go, bmt/bmt.go, eth/handler.go
This PR fixes the staticcheck warning [SA4010](https://staticcheck.dev/docs/checks#SA4010):
The result of append will never be observed anywhere
=> all: fix staticcheck warning SA4010: append result never used

eth/hooks/engine_v1_hooks.go, p2p/discv5/net.go, p2p/discv5/nodeevent_string.go
This PR fixes the staticcheck warning [SA4003](https://staticcheck.dev/docs/checks#SA4003):
Comparing unsigned values against negative values is pointless
- every value of type uint64 is >= 0
- no value of type uint is less than 0
=> fix: staticcheck warning SA4003: every value of uint64 >= 0

XDCxlending/lendingstate/lendingitem_test.go, core/lending_pool_test.go, core/order_pool_test.go
This PR fixes the staticcheck warning [SA5001 Deferring Close before checking for a possible error](https://staticcheck.dev/docs/checks#SA5001):
should check error returned from rpc.DialHTTP() before deferring rpcClient.Close()
=> core, XDCxlending/lendingstate: fix staticcheck warning SA5001

core/blockchain_test.go, p2p/simulations/mocker_test.go, whisper/whisperv6/peer_test.go
This PR fixes the staticcheck warning [SA2002](https://staticcheck.dev/docs/checks#SA2002):
Called testing.T.FailNow or SkipNow in a goroutine, which isn’t allowed
the goroutine calls T.Fatalf, which must be called in the same goroutine as the test
=> all: fix staticcheck warning SA2002: must call T.Fatalf in same goroutine

cmd/faucet/faucet.go, consensus/clique/clique.go, eth/fetcher/fetcher.go
This PR fixes the staticcheck warning [ S1024](https://staticcheck.dev/docs/checks#S1024):
The time.Until helper has the same effect as using x.Sub(time.Now()) but is easier to read.
Before:
```go
x.Sub(time.Now())
```
After:
```go
time.Until(x)
```
should use time.Until instead of t.Sub(time.Now())
=> all: fix staticcheck warning S1024: not use x.Sub(time.Now())

metrics/influxdb/influxdb.go
This PR fixes the staticcheck warning [SA1015](https://staticcheck.dev/docs/checks#SA1015):
using time.Tick leaks the underlying ticker, consider using it only in endless functions, tests and the main package, and use time.NewTicker here.
Before Go 1.23, time.Tickers had to be closed to be able to be garbage collected. Since time.Tick doesn’t make it possible to close the underlying ticker, using it repeatedly would leak memory.
Go 1.23 fixes this by allowing tickers to be collected even if they weren’t closed.
_Put an `✅` in the boxes once you have confirmed below actions (or provide reasons on not …
=> metrics/influxdb: fix staticcheck warning SA1015: replace time.Tick with time.NewTicker

XDCxlending/XDCxlending.go, XDCxlending/lendingstate/relayer.go
This PR fixes the staticcheck warning [S1008: simplify returning boolean expression](https://staticcheck.dev/docs/checks#S1008):
Before:
```go
if <expr> {
return true
}
return false
```
After:
```go
return <expr>
```
=> XDCxlending: fix staticcheck warning S1008: simplify returning boolean expression

core/lending_pool_test.go
This PR fixes the staticcheck warning [S1006: use for {} for infinite loops](https://staticcheck.dev/docs/checks#S1006):
For infinite loops, using for { ... } is the most idiomatic choice.
core/lending_pool_test.go:184:2: should use for {} instead of for true {} (S1006)
=> core: fix staticcheck warning S1006: use for {} for infinite loops

eth/downloader/statesync.go
This PR fixes the staticcheck warning [S1033: unnecessary guard around call to delete](https://staticcheck.dev/docs/checks#S1033):
Calling delete on a nil map is a no-op.
eth/downloader/statesync.go:422:3: unnecessary guard around call to delete (S1033)
=> eth/downloader: fix staticcheck warning S1033: unnecessary guard around call to delete

contracts/utils.go
This PR fixes the staticcheck warning [S1025: unnecessary fmt.Sprintf("%s", x)](https://staticcheck.dev/docs/checks#S1025):
contracts/utils.go:559:9: the argument's underlying type is a slice of bytes, should use a simple conversion instead of fmt.Sprintf (S1025)
n many instances, there are easier and more efficient ways of getting a value’s string representation. Whenever a value’s underlying type is a string already, or the type has a String method, they should be used directly.
Given the following shared definitions
```go
type T1 string
type T2 int
func (T2) String() string { return "Hello, world" }
var x string
var y T1
var z T2
```
we can simplify
```go
fmt.Sprintf("%s", x)
fmt.Sprintf("%s", y)
fmt.Sprintf("%s", z)
```
to
```go
x
string(y)
z.String() 
```
What types of changes does …
=> contracts: fix staticcheck warning S1025: unnecessary fmt.Sprintf("%s", x) 

p2p/peer_test.go
This PR fixes the staticcheck warning [SA4030: ineffective attempt at generating random number](https://staticcheck.dev/docs/checks#SA4030):
Functions in the math/rand package that accept upper limits, such as Intn, generate random numbers in the half-open interval [0,n). In other words, the generated numbers will be >= 0 and < n – they don’t include n. rand.Intn(1) therefore doesn’t generate 0 or 1, it always generates 0.
p2p/peer_test.go:153:32: math/rand.Intn(n) generates a random value 0 <= x < n; that is, the generated values don't include n; rand.Intn(1) therefore always returns 0 (SA4030)
_Put …
=> p2p: fix staticcheck warning SA4030: rand.Intn(1) always returns 0

p2p/rlpx.go
This PR fixes the staticcheck warning [SA4009:  a function argument is overwritten before its first use](https://staticcheck.dev/docs/checks#SA4009):
p2p/rlpx.go:309:59: argument token is overwritten before first use (SA4009)
=> p2p: fix staticcheck warning SA4009: overwrite function argument before first use

p2p/netutil/net.go
This PR fixes the staticcheck warning [SA1021: use bytes.Equal to compare two net.IP](https://staticcheck.dev/docs/checks#SA1021):
A net.IP stores an IPv4 or IPv6 address as a slice of bytes. The length of the slice for an IPv4 address, however, can be either 4 or 16 bytes long, using different ways of representing IPv4 addresses. In order to correctly compare two net.IPs, the net.IP.Equal method should be used, as it takes both representations into account.
p2p/netutil/net.go:215:26: use net.IP.Equal to compare net.IPs, not bytes.Equal (SA1021)
_Put an `✅` in the boxes once you have confirmed below …
=> p2p/netutil: fix staticcheck warning SA1021: use bytes.Equal to compare two net.IP

cmd/utils/flags.go, node/defaults.go
This PR increases default maxpeers to 50. It reduces sync time as it permits more concurrent state retrievals to be running.
Reference: #19497
=> cmd/utils, node: increase default maxpeers to 50

core/txpool/txpool.go, core/types/transaction.go
This PR fixes the bug of very high pending special transactions which is caused by the zero gas price.
When we call:
```go
pending := w.eth.TxPool().Pending(true)
```
in the function `commitNewWork()`. The special transactions are filter out in the function `Pending(enforceTips bool)` because of zero gas price:
```go
// Pending retrieves all currently processable transactions, grouped by origin
// account and sorted by nonce. The returned transaction set is a copy and can be
// freely modified by calling code.
//
// The enforceTips parameter can be used to do an extra filtering on the pending
// transactions and only return those whose **effective** tip is large enough in
// the next pending execution environment.
func (pool *TxPool) Pending(enforceTips bool) …
```
=> core/txpool: fix very high pending special transactions

common/types.go, eth/backend.go, eth/gasprice/feehistory.go, eth/gasprice/feehistory_test.go, eth/gasprice/gasprice.go, eth/gasprice/gasprice_test.go, les/backend.go
This PR upgrades package `eth/gasprice` with below PRs from geth:
- #23886
- #26162
- #27490
- #27909
- #29314
- #30080
And this PR also fixed the wrong gas price with empty blocks.
=> eth/gasprice: fix wrong gas price with empty blocks

internal/web3ext/web3ext.go, node/api.go, p2p/peer.go, p2p/server.go, p2p/server_test.go
This PR adds Add admin_addTrustedPeer and admin_removeTrustedPeer in package rpc.
Reference: #16333
=> rpc: add admin_addTrustedPeer and admin_removeTrustedPeer

core/vm/evm.go, core/vm/instructions_test.go, core/vm/interpreter.go, tests/state_test.go
This PR removes interface `Interpreter`.
Reference: #23111
=> core/vm: remove interface Interpreter

core/state_transition.go
This PR fixes a bug caused by the contract RandomizeSMC(0x0000000000000000000000000000000000000090) in the function `preCheck()` after EIP-1559.
=> core: fix preCheck for RandomizeSMC after EIP-1559

cmd/evm/runner.go, cmd/evm/staterunner.go, internal/debug/flags.go
We should use `GlobalString` and `GlobalBool` if we are using "gopkg.in/urfave/cli.v1".
=> use global function when cli v1

consensus/XDPoS/engines/engine_v2/vote.go
Current check vote threshold is reading current block head, but if there is uncle block with different masternode and penalty node info. It should use the uncle block's information instead of current block head.
=> bug fix use right block to count vote threshold

params/config.go
Increate timeout to 1 min to process all the transaction before timeout kicks in.
If block round number is less then node round number, the block becomes invalid and node won't vote, no QC will generate.
=> increate timeout to 1 min for testnet

cmd/faucet/faucet.go, node/rpcstack_test.go, p2p/simulations/http.go, rpc/http.go
This PR uses http package to replace http method names:
- GET ---> http.MethodGet
- POST ---> http.MethodPost
- DELETE ---> http.MethodDelete,
Ref: #26535
=> all: use http package to replace http method names

core/blockchain_test.go, core/state/statedb.go, core/state_transition.go, core/vm/interface.go, core/vm/runtime/runtime.go
This PR implement [EIP-3651](https://eips.ethereum.org/EIPS/eip-3651).
Reference: #25819
=> implement EIP-3651(warm coinbase)

core/vm/evm.go, core/vm/instructions.go, core/vm/instructions_test.go, core/vm/interpreter.go
This PR improves the reusability of the EVM struct
Reference: #26341
=> core/vm: improve EVM reusability

accounts/abi/abi_test.go, accounts/abi/bind/backends/simulated.go, accounts/abi/bind/backends/simulated_test.go, core/blockchain.go, core/error.go, core/state_processor.go, core/state_transition.go, core/token_validator.go, core/vm/instructions.go, eth/api_tracer.go, eth/tracers/testing/calltrace_test.go, eth/tracers/tracers_test.go, internal/ethapi/api.go, les/odr_test.go, light/odr_test.go, tests/state_test_util.go
this PR separate consensus errors and EVM Internal errors
test contract is following:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;
contract TestRevert {
function revertLogic(address payable recipient)
external
payable
returns (uint256)
{
recipient.transfer(msg.value);
require(msg.value > 10, "Transfer amount must be greater than ten");
return msg.value;
}
// Function to allow contract to send ETH to another account
function sendXDC(address payable recipient, uint256 amount) external returns (uint256){
// Transfer the specified amount to the recipient
recipient.transfer(amount* 1 ether);
return amount;
}
receive() external payable {
}
fallback() external payable {
}
}
```
**eth_estimateGas**
The `curl` command I used:
- address with balance  : …
=> all: improve EstimateGas API 

XDCx/XDCx.go, XDCx/token.go, XDCx/tradingstate/database.go, XDCxDAO/leveldb.go, XDCxDAO/mongodb.go, XDCxlending/XDCxlending.go, XDCxlending/lendingstate/database.go, consensus/XDPoS/XDPoS.go, consensus/XDPoS/engines/engine_v1/engine.go, consensus/XDPoS/engines/engine_v1/snapshot.go, consensus/XDPoS/engines/engine_v1/utils.go, consensus/XDPoS/engines/engine_v2/engine.go, consensus/XDPoS/engines/engine_v2/epochSwitch.go, consensus/XDPoS/engines/engine_v2/snapshot.go, consensus/XDPoS/engines/engine_v2/utils.go, consensus/XDPoS/engines/engine_v2/verifyHeader.go, consensus/XDPoS/utils/types.go, consensus/clique/clique.go, consensus/clique/snapshot.go, consensus/ethash/ethash.go, contracts/utils.go, core/state/trc21_reader.go, eth/fetcher/fetcher.go, eth/handler.go, eth/hooks/engine_v1_hooks.go, eth/hooks/engine_v2_hooks.go, go.mod, go.sum, light/lightchain.go
This PR removes remaining uses of untyped `golang-lru`.
Ref:
- #26162
- #26194
=> all: remove uses of untyped golang-lru

consensus/XDPoS/engines/engine_v2/epochSwitch.go, consensus/XDPoS/engines/engine_v2/timeout.go, consensus/tests/engine_v2_tests/sync_info_test.go, core/types/consensus_v2.go, params/version.go
Fix tc cross epoch different masternode counts issue
Found out by testnet issue, node start sending sync info message, because one of node not functioning (normal). And Sync Info Message contains latest TC and QC. But TC is generated by last epoch which only have 17 signatures but current epoch requires 19 signatures. So sync info is not accepting by all the nodes. Cause some nodes are at old round and some nodes are at new round.
When process TC, it should use the right epoch information, not the current epoch / round information.
When send timeout message, node also save timeout message into local pool, and we have XDPoS_getLatestPoolStatus to receive signer. But we only assign signer while verify incoming timeout.
_Put an …
=> Fix tc cross epoch different masternode counts issue

accounts/abi/bind/backends/simulated.go, core/state_processor.go, core/state_transition.go, core/token_validator.go, eth/api_tracer.go, eth/tracers/testing/calltrace_test.go, eth/tracers/tracers_test.go, internal/ethapi/api.go, les/odr_test.go, light/odr_test.go, tests/state_test_util.go
The following 3 commits address the incompletely resolved issues in #632 :
1. Simplify the return values of the function `TransitionDb` and related functions to align them with the upstream code.
2. The changes from the previous PR caused an issue where the `execution reverted` message was not correctly returned. This happened because, in cases of insufficient balance, a revert is required without a return value, which was not properly handled. Therefore, the condition checking for a non-zero length of return values has been removed, allowing `newRevertError` to handle this scenario.
3. The upstream function returns a wrapped error:
```go
if st.gas < gas {
return nil, fmt.Errorf("%w: have %d, want %d", ErrIntrinsicGas, st.gas, gas), nil
}
```
We should use `errors.Is(err, …
=> all: simplify function TransitionDb

XDCx/XDCx.go, XDCxlending/XDCxlending.go, core/blockchain.go, eth/backend.go, ethstats/ethstats.go, les/backend.go, light/lightchain.go, node/node.go, node/node_example_test.go, node/service.go, node/utils_test.go, p2p/simulations/adapters/exec.go, p2p/simulations/examples/ping-pong.go, p2p/simulations/http_test.go, p2p/testing/protocoltester.go
This PR removes the empty function `SaveData()` from all services except `BlockChain`. The function `SaveData()` is implemented by the `BlockChain` service only, and it is called in two places repeatedly when chain was stopped:
First:
```go
func (n *Node) Stop() error {
......
for _, service := range n.services {
service.SaveData()
}
......
}
```
Second:
```go
func (bc *BlockChain) Stop() {
......
bc.SaveData()
......
}
```
So we can call `SaveData()` only once in the function `Stop()` of `BlockChain`, and remove `SaveData()` in other services. 
```go
func (bc *BlockChain) SaveData() {
bc.wg.Add(1)
defer bc.wg.Done()
bc.mu.Lock()
defer bc.mu.Unlock()
......
```
Then the uses of `wg` and `mu` in the function of  `saveData()` can also be removed.
What types of changes does your code …
=> all: remove empty function SaveData()

core/blockchain.go, core/blockchain_test.go, core/database_util.go, core/database_util_test.go, core/headerchain.go, core/rawdb/accessors_chain.go, core/rawdb/accessors_indexes.go, core/rawdb/accessors_metadata.go, core/rawdb/schema.go, internal/syncx/mutex.go, light/lightchain.go, light/lightchain_test.go, light/txpool.go
This PR upgrade the `core` package by the following PRs from geth:
- #18436
- #20287
- #21480
- #22853
- #23576
- #27475
We will submit another PR to improve the function `reorg` after test.
=> upgrade the core package for reorg

crypto/bn256/cloudflare/gfp12.go, crypto/bn256/gnark/g1.go, crypto/bn256/gnark/g2.go, crypto/bn256/gnark/gt.go, crypto/bn256/gnark/pairing.go, crypto/bn256/google/bn256.go, crypto/bn256/google/gfp12.go, crypto/crypto.go, crypto/ecies/ecies.go, crypto/secp256k1/curve.go, crypto/secp256k1/scalar_mult_cgo.go, crypto/secp256k1/scalar_mult_nocgo.go, crypto/secp256k1/secp256_test.go, crypto/signature_cgo.go, crypto/signature_nocgo.go, crypto/signature_test.go, go.mod, go.sum, tests/fuzzers/bn256/bn256_fuzz.go, tests/fuzzers/secp256k1/secp_test.go
This PR updates the `crypto` package by the following PRs from the geth:
- #28946
- #29307
- #29889
- #30126
- #30595
- #30585
- #30974
TODO: #29050
=> upgrade crypto package

.gitignore, .golangci.yml, Makefile, build/checksums.txt, build/ci.go, go.mod, internal/build/archive.go, internal/build/download.go, internal/build/gotool.go, internal/build/util.go
This PR make `build/ci.go` to download and run `golangci-lint`.
Usage: `make lint`
=> build: support golangci-lint v1.63.4

core/types/lending_transaction.go, core/types/order_transaction.go, core/types/transaction.go
The file `core/types/gen_access_tuple.go` has been deleted in the PR #526. But the go generate directive was forgotten to be deleted.
=> core/types: remove generate directive for gen_tx_json.go

Makefile, build/ci.go, internal/build/file.go
This PR add a checker for  'go mod tidy' which can be called by `make check_tidy`.
=> build: add 'go mod tidy' checker

cmd/abigen/main.go
This PR picks #31045 from geth.
=> cmd/abigen: require either '--abi' or '--combined-json'

core/blockchain.go, core/types/transaction.go
This PR refactor the function `reorg` according to below PRs from geth:
- #23761
- #24616
- #24996
- #30600
=> core: refactor the function reorg

core/blockchain.go, light/lightchain.go
This PR handles the nil return value of the function `GetBlockNumber` and fixes the issue #817.
=> core, light: handle the nil return value of `GetBlockNumber`

XDCxDAO/leveldb.go, cmd/XDC/chaincmd.go, cmd/XDC/consolecmd_test.go, cmd/XDC/dao_test.go, cmd/gc/main.go, cmd/utils/flags.go, consensus/XDPoS/engines/engine_v2/snapshot_test.go, core/bench_test.go, core/rawdb/database.go, eth/backend.go, eth/filters/bench_test.go, eth/filters/filter_test.go, ethdb/leveldb/leveldb.go, node/node.go, node/service.go, node/service_test.go, trie/trie_test.go
This PR introduces the "Read-Only" database.
Ref: #22407
=> all: add read-only option to database

cmd/XDC/chaincmd.go, cmd/XDC/dbcmd.go, cmd/XDC/main.go
This PR introduces:
- `db.put`: put a value into the database
- `db.get`: read a value from the database
- `db.delete`: delete a value from the database
- `db.stats`: check compaction info from the database
- `db.compact`: trigger a db compaction
Ref: #22014
=> cmd/XDC: add db commands: stats, compact, put, get, delete

core/blockchain.go
This PR improves the output format of report block:
Old format:
```text
ERROR[02-05|12:47:41.321] "\n########## BAD BLOCK #########\nChain config: {\"chainId\":50,\"homesteadBlock\":1,\"eip150Block\":2,\"eip150Hash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"eip155Block\":3,\"eip158Block\":3,\"byzantiumBlock\":4,\"XDPoS\":{\"period\":2,\"epoch\":900,\"reward\":5000,\"rewardCheckpoint\":900,\"gap\":450,\"foudationWalletAddr\":\"0x92a289fe95a85c53b8d0d113cbaef0c1ec98ac65\",\"SkipV1Validation\":false,\"v2\":{\"SwitchEpoch\":89300,\"switchBlock\":80370000,\"config\":{\"maxMasternodes\":108,\"switchRound\":0,\"minePeriod\":2,\"timeoutSyncThreshold\":3,\"timeoutPeriod\":30,\"certificateThreshold\":0.667,\"expTimeoutConfig\":{\"base\":1,\"maxExponent\":0}},\"allConf …
```
=> core: improve the output format of report block

core/vm/eips.go, core/vm/instructions_test.go, core/vm/jump_table.go, core/vm/opcodes.go
This PR implements the `BLOBHASH` opcode 0x49 for EIP-4844.
Ref: #27356
=> core/vm: implement the BLOBHASH opcode 0x49

eth/backend.go, eth/ethconfig/config.go, eth/protocol_test.go, les/backend.go, les/server.go
This PR improves the user experience when creating a private network because the `--networkid` flag doesn't need to be specified anymore.
=> eth: set networkID to chainId by default

cmd/XDC/config.go, cmd/utils/flags.go, cmd/utils/flags_legacy.go
This PR deprecates the flag `--mine`. This flag is not used really.
=> cmd: deprecate the `--mine` flag

cmd/utils/flags.go, cmd/utils/flags_legacy.go
This PR deprecates flag `--XDCx-datadir` since this directory is always `<node_data_dir>/XDCx`.
=> cmd/utils: deprecate flag `--XDCx-datadir`

cmd/XDC/consolecmd_test.go, cmd/utils/flags.go
This PR changes the default value of some flag to simplify sync. So the users don't need to set many flags in the script. The change log is as follows:
|           flag |   old value |                                    new value |
| -------------: | ----------: | -------------------------------------------: |
|      etherbase |         "0" | "0x000000000000000000000000000000000000abcd" |
|            rpc |       false |                                         true |
|        rpcaddr | "localhost" |                                    "0.0.0.0" |
|         rpcapi |          "" | ""eth,debug,net,txpool,personal,web3,XDPoS"" |
|  rpccorsdomain |          "" |                                          "*" |
|      rpcvhosts | "localhost" |                                          "*" |
| …
=> cmd/utils: change default value of some flags to simplify sync

cmd/XDC/config.go, cmd/XDC/consolecmd.go, cmd/utils/flags.go
This PR replaces `utils.GroupFlags` with `slices.Concat`
=> cmd: use slices.Concat instead of GroupFlags

cmd/utils/flags.go, common/constants.go, common/constants/constants.go.devnet, common/constants/constants.go.local, common/constants/constants.go.testnet, eth/backend.go
The PR #850 sets network ID automatically. And the PR #846 copy constants during XDC startup. But when the flag `NetworkIdFlag` is not provide by script, the function `common.CopyConstans` in `SetEthConfig` does not work. So I move it  into the function `New` in the file `eth/backend.go` after networkID has been determined.
=> cmd, common, eth: copy constants after get chain id

cmd/utils/flags.go
This PR disables kzg4844 since we did not use it to support solidity v0.8.24.
=> cmd/utils: disable kzg4844

common/constants.devnet.go, core/vm/interpreter.go, core/vm/jump_table.go
This PR enables cancun instruction set
=> core/vm: enable cancun instruction set

node/config.go, node/node.go, node/service.go
This PR applies geth PR #18199.
=> node: warn when using deprecated config/resource files

cmd/XDC/dbcmd.go, cmd/utils/cmd.go, core/rawdb/accessors_chain.go, core/rawdb/database.go, core/rawdb/schema.go
This PR is the successor of PR #821:
- add db command: inspect
- some minor improvements for other db commands
Ref: 
- #19244
- #22014
=> cmd/XDC, core/rawdb: add db command inspect

cmd/utils/flags.go
This PR fixes a bug about `Etherbase` which is introduced in PR #855. The `Etherbase` is set to the default value `0x000000000000000000000000000000000000abcd` only for the purpose of sync when the flag `--etherbase` is not set. But this new feature conflicts with the flag `--unlock`. We should not set `Etherbase` to any value when the flag `--etherbase` is set and  `--etherbase` is not set.
TODO: #30737
=> cmd/utils: not set Etherbase when flag `--unlock` is set

core/blockchain.go
=> core: remove the duplicate function `getProcInterrupt()`

core/headerchain.go
This PR fixes a bug in the function `ValidateHeaderChain`: integer divide by zero
Ref: #16904
=> core: fix integer divide by zero in the function `ValidateHeaderChain`

core/blockchain.go, core/rawdb/accessors_chain.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/modes.go, eth/downloader/queue.go, eth/downloader/statesync.go, eth/handler.go, les/handler.go
This PR upgrade `eth/downloader` with the following geth PRs:
- #17510
- #17956
- #17839
- #17983
- #18085
- #18335
- #19232
- #19413
- #21067
- #21201
=> upgrade downloader

cmd/XDC/config.go, cmd/XDC/main.go, cmd/utils/flags.go, common/constants.all.go, core/blockchain.go, eth/backend.go
This PR:
- removes the flags  `rewound` and `rollback` because they are used rarely
- introduces a new flag `set-head` to rollback quicker, usage: `XDC --set-head 48` or `XDC --set-head 0x30`
**Notice: the value of `set-head` must be greater than 0.**
=> cmd, common, core:  optimize rollback by flag

core/chain_makers.go, eth/downloader/downloader_test.go, eth/downloader/testchain_test.go
This PR reworks the downloader tests so they share a common test blockchain instead of generating a chain in every test.
Ref: #17916
TODO: make `testSyncProgress` run successfully for mode `FastSync`.
=> eth/downloader: speed up tests by generating chain only once

cmd/utils/utils.go
If the function `eth.New` returns `nil, err` and the caller does not handle err, then XDC will panic, such as:
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xef7cba]
goroutine 1 [running]:
github.com/XinFinOrg/XDPoSChain/eth.(*Ethereum).Protocols(...)
/home/me/XDPoSChain/eth/backend.go:553
github.com/XinFinOrg/XDPoSChain/cmd/utils.RegisterEthService.func2(0xc000694200)
/home/me/XDPoSChain/cmd/utils/utils.go:42 +0x15a
github.com/XinFinOrg/XDPoSChain/node.(*Node).Start(0xc0004b22c8)
/home/me/XDPoSChain/node/node.go:226 +0x5ce
github.com/XinFinOrg/XDPoSChain/cmd/utils.StartNode(0xc0004b22c8)
/home/me/XDPoSChain/cmd/utils/cmd.go:68 +0x1c
main.startNode(_, _, {{0x0, 0x141f, 0x0, 0x1, 0x0, 0x64, …
```
=> cmd/utils: handle err returned by eth.New to fix panic

.github/workflows/ci.yml, Dockerfile, Dockerfile.bootnode, Dockerfile.node, Makefile, build/ci.go, cicd/Dockerfile, go.mod
Go 1.23 has brought many performance improvements and stability fixes, including issue mentioned in #832. With Go 1.24 coming out soon (expected in February 2025), upgrading to Go 1.23 now will help us prepare for future version changes. So this PR upgrades the codebase to Go 1.23 to make the code more reliable and easier to maintain.
=> all: update to go version 1.23

core/genesis.go, core/genesis_test.go, light/postprocess.go, params/config.go
This PR:
- remove ethereum network variables: mainnetCheckpoint, ropstenCheckpoint, MainnetGenesisHash
- rename XDCMainnetGenesisHash to MainnetGenesisHash
- update value of DevnetGenesisHash
=> core, light, params: remove genesis hash of ethereum network

core/chain_indexer.go, core/chain_indexer_test.go, eth/backend.go, eth/bloombits.go, les/backend.go, les/commons.go, les/distributor.go, les/handler.go, les/helper_test.go, les/odr_test.go, les/request_test.go, les/retrieve.go, les/server.go, light/lightchain.go, light/odr.go, light/postprocess.go
This PR enables the indexers to work in light client mode by downloading a part of these tries (the Merkle proofs of the last values of the last known section) in order to be able to add new values and recalculate subsequent hashes. 
Ref: #16534
=> light: CHT and bloom trie indexers working in light mode

core/chain_indexer.go, eth/backend.go, eth/bloombits.go, params/network_params.go
This PR make chain indexers configurable, which will definitely help unit tests and avoid making thousands of blocks to generate an indexer element.
Notice: the packages les and light are not update because they will be removed soon.
Ref: #17188
=> core, eth, params: make indexer configurable

eth/downloader/downloader.go, eth/downloader/statesync.go
=> eth/downloader: fix peer idleness tracking when restarting statesync

common/constants.local.go
This PR makes cancun available by default in the private network.
=> common: set cancun block to 0 for local net

cmd/XDC/chaincmd.go
This PR does not handle the network flag when init genesis. We can support network name and genesis file as parameter now.
Before this PR, we can init genesis by the network flag, such as:
```shell
XDC init --devnet
```
But the above way does not report error if the data dir has been initialize:
```shell
rm -rf ~/.XDC/
XDC init --mainnet
XDC init --devnet
```
If we don't use network flag, then the result is as expected:
```shell
rm -rf ~/.XDC/
XDC init mainnet
XDC init devnet
```
=> cmd/XDC: improve init genesis

cicd/devnet/genesis.json, cicd/testnet/genesis.json, cmd/XDC/chaincmd.go, core/genesis.go, genesis/devnet.json, genesis/testnet.json
This PR fixes the wrong genesis hash by set:
- `common.Eip1559Block`
- `eip1559Block` in genesis file for devnet and testnet
Any of the above methods can fix the issue.
Test:
```shell
make all
./build/bin/XDC init devnet
```
Result:
```text
INFO [03-13|11:12:52.989] Maximum peer count                       ETH=50 total=50
INFO [03-13|11:12:52.990] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [03-13|11:12:52.990] Set etherbase                            address=xdc000000000000000000000000000000000000ABcD
INFO [03-13|11:12:52.991] Set global gas cap                       cap=50,000,000
INFO [03-13|11:12:52.991] XDCX datadir                             path=/home/me/.XDC/XDCx
INFO [03-13|11:12:52.992] Allocated cache and file …
```
=> all: fix wrong genesis hash by set EIP-1559 number

params/config.go
This PR fixes wrong values in `DevnetChainConfig`:
```go
HomesteadBlock: big.NewInt(1),
EIP150Block:    big.NewInt(2),
EIP155Block:    big.NewInt(3),
EIP158Block:    big.NewInt(3),
ByzantiumBlock: big.NewInt(4),
```
They should be zero according to the latest genesis of devnet.
=> params: fix outdated DevnetChainConfig

Makefile, build/ci.go, internal/build/util.go
This PR adds a new command `make quick-test` to skip time-consuming tests. This command saves much test time during development.
=> build: add command `make quick-test` to save test time

cmd/utils/flags.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go
This flag is leftover from the swarm era. It's useless now.
Ref: #30705
=> cmd/utils, eth/ethconfig: remove flag docroot

eth/api_backend.go, internal/jsre/deps/web3.js, rpc/types.go
This PR accepts `finalized` as block number as geth. This keyword is same as `committed` in our codebase.
=> rpc: support keyword `finalized` as block number

p2p/message.go, p2p/metrics.go, p2p/peer.go, p2p/rlpx.go
This PR aims to fix issue #862 by adding and improving monitoring metrics related to block and transaction propagation in blockchain networks. Specifically, it introduces new metrics to better monitor Snappy compressed wire traffic for different subprotocols, down to the message type level. The new metrics include:
- `p2p/{ingress|egress}/eth/{version}/{msgCode}`: These are message type level metrics from `xdcpos` and other protocols.
These metrics help the team understand data flow in the network more clearly, optimizing blockchain performance and stability. The metrics are also displayed in the monitor for real-time tracking and analysis.
Here is how these metrics appear in the monitor …
=> p2p: measure subprotocol bandwidth usage

cmd/XDC/chaincmd.go, cmd/XDC/dbcmd.go, cmd/XDC/main.go, cmd/utils/flags.go
This PR groups all built-in network flags together and list them in the command as a whole. And all database path flags are also grouped, since they are used together usually .
Ref: #24698
=> cmd: group network and database flags together

consensus/tests/engine_v1_tests/helper.go, consensus/tests/engine_v2_tests/helper.go, contracts/validator/validator_test.go, core/blockchain_test.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_test.go
apply the following PRs from geth:
- #17383
- #19127
- #19953
- #20481
Ref: 
#18486
=> core/state: optimize state management and storage iteration

Dockerfile, Dockerfile.bootnode, Dockerfile.node, cicd/Dockerfile
fixes the below build warning
`WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1) `
=> cicd: fix warning when build docker

build/deb/completions/bash_autocomplete, build/deb/completions/install.sh, build/deb/completions/zsh_autocomplete
supports auto-completion for bash. 
command:
```bash
./XDPoSChain/build/deb/completions/install.sh
```
output:
example 1:
```bash
XDC [TAB]
```
output:
---
example 2:
```bash
XDC a[TAB]
```
output:
=> build: support auto-completion for bash

common/constants.testnet.go
change `cancunBlock` from 71550000 to 71551800 for testnet which is 1800 blocks after eip1559Block
=> common: enable cancun after 1800 blocks in eip1559 on testnet

trie/database.go
This PR removes the second copy which reduces allocated memory by quite a bit.
Ref: #21261
=> trie: reduce allocs in insertPreimage #21261

eth/backend.go
fix some typo mistake and simplify switch-case
=> eth: some typo mistake

rpc/errors.go, rpc/http.go, rpc/http_test.go, rpc/types.go
=> rpc: add HTTPError type for HTTP error responses #22677

common/format.go, core/blockchain.go, core/headerchain.go
This PR adds an `age` field to all the import logs (receipt, block, header) and also to the "loaded most recent" logs. 
=> common, core: add block age into info logs #17718

core/blockchain.go
- extract common code in function `insertChain` and `getResultBlock` to a new function `processTradingAndLendingStates`
- return err when `IsEpochSwitch` fails:
Old code:
```go
isEpochSwithBlock, epochNumber, err := engine.IsEpochSwitch(block.Header())
if err != nil {
log.Error("[insertChain] Error while checking if the incoming block is epoch switch block", "Hash", block.Hash(), "Number", block.Number())
bc.reportBlock(block, nil, err)
}
```
New code:
```go
isEpochSwithBlock, epochNumber, err := engine.IsEpochSwitch(block.Header())
if err != nil {
log.Error("[insertChain] Error while checking if the incoming block is epoch switch block", "Hash", block.Hash(), "Number", block.Number())
bc.reportBlock(block, nil, err)
return statedb, tradingState, lendingState, err
}
```
What types of …
=> core: simplify code of trading and lending state

internal/ethapi/api.go
=> internal/ethapi: accept both hex and decimal for blockCount #23363

XDCx/XDCx.go, XDCxlending/XDCxlending.go, consensus/XDPoS/XDPoS.go, consensus/clique/clique.go, eth/backend.go, internal/ethapi/backend.go, node/api.go, p2p/simulations/adapters/exec.go, rpc/types.go
=> all: remove version field #25096

rpc/client_test.go, rpc/errors.go, rpc/handler.go, rpc/json.go, rpc/server_test.go, rpc/service.go, rpc/testdata/internal-error.js, rpc/testservice_test.go
This changes the error code returned by the RPC server in certain situations:
- handler panic: code -32603
- result marshaling error: code -32603
- attempt to subscribe via HTTP: code -32001
In all of the above cases, the server previously returned the default error code -32000.
geth: #25678
=> rpc: improve error codes for internal server errors #25678

rpc/context_headers.go, rpc/http.go, rpc/http_test.go
This adds a way to specify HTTP headers per request.
geth: #26023
=> rpc: support injecting HTTP headers through context #26023

internal/guide/guide_test.go
This removes an RPC test which takes > 90s to execute, and updates the internal/guide tests to use lighter scrypt parameters.
geth: #26193
=> rpc, internal/guide: speed up tests a bit #26193

cmd/XDC/main.go, cmd/utils/flags.go, eth/api_backend.go, eth/backend.go, internal/ethapi/api.go, internal/ethapi/backend.go, node/config.go, node/rpcstack_test.go
This PR prevents users from submitting transactions without EIP-155 enabled.
Replay protection is important so we should gently force our users to use it.
It changes the JSON-RPC API quite significantly, so if you see the "only replay-protected (EIP-155) transactions allowed over RPC" error, you know that you need to update your signer.
my test script
```javascript
import { ethers } from "ethers";
async function testTransaction() {
const provider = new ethers.providers.JsonRpcProvider("http://0.0.0.0"); //  replace with your RPC address
const wallet = new ethers.Wallet("your private key", provider); // replace with your private key
const nonce = await provider.getTransactionCount(wallet.address);
const currentGasPrice = await provider.getGasPrice();
const fakeTx = {
nonce: nonce, …
```
=> internal/ethapi: disable sending of non eip155 replay protected tx #22339

cmd/XDC/main.go, cmd/utils/flags.go, go.mod, go.sum, node/api.go, node/config.go, node/defaults.go, node/endpoints.go, node/jwt_handler.go, node/node.go, node/node_test.go, node/rpcstack.go, node/rpcstack_test.go, rpc/server.go, rpc/types.go
This PR implements support for JWT. An rpc.API can now be Authenticated, meaning that it will only be exposed over an authenticated API point, meaning:
- ipc,
- or http endpoint with jwt support,
- or ws endpoint with jwt support.
=> cmd/geth, node, rpc: implement jwt tokens #24364

cmd/XDC/main.go, cmd/utils/flags.go, node/config.go, node/defaults.go, node/node.go
The default listening address "localhost" is not sufficient when running XDC in Docker.
=> cmd/XDC: make authrpc listening address settable from command line #24522

core/block_validator.go, core/blockchain.go, core/blockchain_insert.go, core/blockchain_test.go, core/types.go
This is a tiny PR to use headers in a few places where we used blocks previously, but were unnecessary.
geth: #19261
=> core: use headers only where blocks are unnecessary #19261

rpc/ipc_unix.go
This change fixes a minor flaw in the check for ipc endpoint length. The max_path_size is the max path that an ipc endpoint can have, which is 208. However, that size concerns the null-terminated pathname, so we need to account for an extra null-character too.
geth: #26614
=> rpc: fix off-by-one in ipc endpoint length check #26614

rpc/websocket.go
This increases the maximum allowed message size to 32MB.
Originally submitted at https://github.com/ledgerwatch/erigon/pull/2739
example block failure: https://etherscan.io/tx/0x1317d973a55cedf9b0f2df6ea48e8077dd176f5444a3423368a46d6e4db89982#internal
geth: #26883
=> rpc: increase websocket frame size #26883

node/api.go, node/config.go, node/jwt_auth.go, node/jwt_handler.go, node/node.go, node/node_auth_test.go, node/rpcstack_test.go, rpc/client.go, rpc/client_opt.go, rpc/client_opt_test.go, rpc/http.go, rpc/ipc.go, rpc/server.go, rpc/stdio.go, rpc/websocket.go
This PR:
* Implements testing of the RPC authentication conditions as specified by the Engine API authentication spec
* Adds getters to the node to retrieve the WS and HTTP auth endpoints (useful for testing when the port is assigned dynamically, mirrors the existing getters for non-auth endpoints)
* Implements `rpc.DialWithAuth`, `rpc.DialHTTPWithAuth`, `rpc.DialWebsocketWithAuth` that take a `rpc.HeaderAuthProvider` and implemented with `rpc.JWTAuthProvider` (along with simple test-only implementations). Thanks to @trianglesphere for implementing this
* Tests the authentication:
* That the engine and eth modules are available
* That basic auth works
* That other secrets don't work
* That the "none" algorithm trick doesn't work
* That the issued-at time is verified with the spec 60 …
=> node, rpc: add JWT auth support in client #24911

internal/cmdtest/test_cmd.go, rpc/client.go
This change gives the cmd-tests have a bit more time to finish before getting forcibly torn down.
geth: #27083
=> rpc, internal/cmdtest: increase timeout in tests #27083

rpc/client_opt.go, rpc/server_test.go, rpc/testservice_test.go, rpc/websocket.go, rpc/websocket_test.go
This change adds a configurable limit to websocket message.
geth: #27801
=> eth, rpc: add configurable option for wsMessageSizeLimit #27801

rpc/types.go, rpc/types_test.go
The String() version of BlockNumberOrHash uses decimal for all block numbers, including negative ones used to indicate labels. Switch to using BlockNumber.String() which encodes it correctly for use in the JSON-RPC API.
geth: #28358
=> rpc: fix eth_getBlockReceipts when using block numbers or labels #28358

node/defaults.go, node/node.go, node/rpcstack.go, rpc/http.go, rpc/http_test.go, rpc/server.go, rpc/websocket_test.go
Adds a configurable HTTP request limit, and bumps the engine default
geth: #28948
=> node, rpc: add configurable HTTP request limit #28948

rpc/handler.go
=> rpc: truncate call error data logs #30028

rpc/server.go
Here we add distinct error messages for network timeouts and JSON parsing errors. Note this specifically applies to HTTP connections serving a single RPC request.
geth: #30191
=> rpc: show more error detail for invalidMessageError #30191

eth/downloader/downloader.go, eth/handler.go, eth/tracers/testing/calltrace_test.go, node/api_test.go, node/node_test.go, node/rpcstack_test.go, p2p/peer.go, rlp/decode_test.go, rlp/rlpgen/gen_test.go, rpc/client_test.go, rpc/types_test.go, tests/state_test.go
This PR removes the code of copy loop var.
Previously, the variables declared by a “for” loop were created once and updated by each iteration. In Go 1.22, each iteration of the loop creates new variables, to avoid accidental sharing bugs.
=> all: not copy loop var for golang v1.22

internal/web3ext/web3ext.go
This PR cleans the file `web3ext.go`, removes deprecated JSONRPC APIs:
- debug_backtraceAt
- debug_setMutexProfileRate
The function `BacktraceAt` has been removed in PR #734 and #28187.
=> internal/web3ext: remove deprecated debug api

cmd/bootnode/main.go, internal/debug/api.go
The `debug_verbosity` JSONRPC api calls the function `Verbosity(level int)` in the file `internal/debug/api.go`. The type of parameter `level` is `slog.Level`:
```go
const (
LevelDebug Level = -4
LevelInfo  Level = 0
LevelWarn  Level = 4
LevelError Level = 8
)
```
But in fact we use `log.FromLegacyLevel` as input now:
```go
const (
legacyLevelCrit = iota
legacyLevelError
legacyLevelWarn
legacyLevelInfo
legacyLevelDebug
legacyLevelTrace
)
```
=> cmd, debug: fix debug_verbosity

node/jwt_handler.go, node/rpcstack_test.go
`http.StatusUnauthorized` seems more suitable.
Use `401 Unauthorized` for JWT auth failures (missing/invalid/expired tokens) because it means "invalid credentials."  
`403 Forbidden` means "no permission," not auth failure. So `401` is more accurate.  
=> node: change JWT error status to 401 Unauthorized #25629

core/vm/evm.go
This PR fixes the bug of `invalid merkle root` which is introduced in PR #627. When we sync with mainnet from genesis, the progress is stuck at block 34059322:
```text
ERROR[05-07|09:44:23.105] 
########## BAD BLOCK #########
Number: 34059322
Hash: 0x27cad6c05e6881288549064ee071941e99bbc235552cc93e6ad5896a387a90ff
Round: 0
Error: invalid merkle root (remote: f2a379074af51d343d0a6aa1cfd731e223284f409e6fb32e84cc95014c3be98b local: 519135ccfebd30abe494d636ce3e67b23010e7dc6189e32e71800734eb260a6c)
```
This bug only occurs when StaticCall is called in tx and the block number is less than TIPXDCXCancellationFee:
- mainnet: 38383838
- testnet: 23779191
Which part of the codebase this PR will touch …
=> core/vm: fix invalid merkle root caused by PR #627

cmd/utils/flags.go, node/node.go
Removes the ability to pass a JWT secret in plaintext via CLI.This should help users not reveal their secret e.g. in bug reports
=> node: allow JWT pass by file only #24579

eth/downloader/downloader_test.go
=> eth/downloader: improve test

cmd/XDC/main.go, cmd/utils/flags.go
PR #997 prefetches next block state concurrently. But this feature has a slight conflict with our current consensus algorithm. It produces `ErrUnknownAncestor` during sync, disconnect and reconnect peer.
=> cmd: disable prefetch next block state by default

core/types/block.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/metrics.go, eth/downloader/peer.go, eth/downloader/peer_test.go, eth/downloader/queue.go, eth/downloader/queue_test.go, eth/downloader/resultstore.go, eth/downloader/statesync.go, eth/fetcher/fetcher.go
=> eth/downloader: refactor downloader and queue #21263

accounts/abi/bind/backends/simulated.go, cmd/XDC/main.go, cmd/utils/flags.go, core/blockchain.go, core/state/database.go, eth/api_tracer.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, eth/state_accessor.go, trie/database.go, trie/secure_trie.go
This PR offers an advanced command line flag for not saving preimages of trie keys.
It's useful for node operators to reduce a few disk usage if the preimages are unnecessary.
Ref: #21402
=> all: disable recording preimage of trie keys #21402

trie/database.go
Decrease children size instead of dirties size when marking dirties as cleaned up in trie cleaner
Ref: #25007
=> trie: fix size accounting in cleaner #25007

core/state/state_test.go, core/state/statedb_test.go
=> core/state: remove toAddr helper in tests #22772

core/state/sync_test.go, trie/sync_test.go
=> core, trie: speed up some tests with quadratic processing flaw #21987

cmd/XDC/consolecmd.go, cmd/XDC/consolecmd_test.go, cmd/XDC/main.go, cmd/utils/flags.go, console/console.go, node/config.go, node/node.go
=> cmd, console, node : deprecate personal namespace #26390

cmd/XDC/accountcmd.go, cmd/XDC/main.go, internal/ethapi/api.go
=> cmd, internal/ethapi: avoid panic if keystore is not available #27039

cmd/XDC/accountcmd.go, cmd/XDC/config.go, node/config.go, node/node.go
=> cmd/XDC: accountcmd no need to acquire the datadir lock #27084

consensus/XDPoS/api.go, consensus/XDPoS/utils/types.go, consensus/tests/engine_v2_tests/api_test.go
Make XDPoS_getBlockInfoByEpochNum accept v1 epoch numbers. In the backend we can use math to calculate v1 epoch block numbers since each epoch is fixed to 900 blocks in v1 consensus.
=> make XDPoS_getBlockInfoByEpochNum work with v1 epoch number

crypto/bn256/cloudflare/mul_arm64.h
=> crypto: pull in upstream fix for R27 and R29 usage #32057

eth/tracers/tracers_test.go
=> eth/tracers: fix benchmarks #23806

consensus/XDPoS/XDPoS.go, consensus/XDPoS/engines/engine_v1/engine.go, consensus/consensus.go, consensus/ethash/consensus.go, consensus/tests/engine_v2_tests/verify_header_test.go, core/blockchain.go, core/blockchain_test.go, eth/api_tracer.go, eth/handler.go
no need to verify header when trace block since the block has been verified before import.
=> eth: skip VerifyHeader in traceBlock to fix #1185

core/state/database.go, core/state/dump.go, core/state/iterator.go, core/state/state_object.go, core/state/statedb.go, core/state/sync.go, core/state/sync_test.go, core/types/state_account.go, trie/secure_trie.go, trie/trie.go, trie/trie_test.go
=> core/state: move state account to core/types + abstracted write account to trie #23567

cmd/utils/flags.go, core/evm.go, eth/api.go, eth/api_backend.go, eth/state_accessor.go, eth/tracers/api.go, eth/tracers/api_test.go, internal/ethapi/transaction_args.go
=> eth/tracers: move tracing APIs into eth/tracers #22161 #22473

eth/tracers/api.go, eth/tracers/api_test.go
=> eth/tracer: extend call tracer #22245

consensus/XDPoS/api.go, core/evm.go, core/vm/evm.go, core/vm/instructions.go, core/vm/runtime/runtime.go, core/vm/runtime/runtime_test.go, eth/tracers/testing/calltrace_test.go, eth/tracers/tracers_test.go, tests/vm_test_util.go
=> core/vm: make time field use uint64 #26474

trie/iterator.go, trie/iterator_test.go, trie/trie.go
=> trie: implement NodeBlob API for trie iterator #24391

eth/filters/api.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go
=> eth/filters: eth_getLogs fast exit for invalid block range #28386

accounts/usbwallet/trezor.go
=> accounts/usbwallet: full 32bit chainId support for Trezor #17439

ethstats/ethstats.go
=> ethstats: avoid blocking chan when received invalid stats request #21073

ethstats/ethstats.go, ethstats/ethstats_test.go
=> ethstats: fix URL parser for '@' or ':' in node name/password #21640

core/evm.go, eth/tracers/api.go, eth/tracers/api_test.go, internal/ethapi/api.go
=> eth/tracers: add support for block overrides in debug_traceCall #24871

eth/api_backend.go, eth/tracers/api.go, ethclient/gethclient/gethclient_test.go, internal/ethapi/api.go, internal/ethapi/backend.go, internal/ethapi/transaction_args_test.go, internal/web3ext/web3ext.go
=> internal/ethapi: add block overrides to eth_call #26414

eth/tracers/api_test.go, eth/tracers/internal/tracetest/flat_calltrace_test.go, eth/tracers/internal/util.go, eth/tracers/js/tracer_test.go, eth/tracers/logger/access_list_tracer.go
=> eth/tracers: fix mismatched names in comments #29348

eth/tracers/js/goja.go, eth/tracers/logger/logger.go, eth/tracers/native/call.go
Ref: #30332
Make tracers more robust by handling `nil` receipt as input. Also pass in a receipt with gas used in the state test runner. Closes https://github.com/ethereum/go-ethereum/issues/30117.
=> eth/tracers: avoid panic in state test runner #30332

accounts/abi/abigen/bindv2_test.go, accounts/abi/abigen/source2.go.tpl, accounts/abi/abigen/testdata/v2/callbackparam.go.txt, accounts/abi/abigen/testdata/v2/crowdsale.go.txt, accounts/abi/abigen/testdata/v2/dao.go.txt, accounts/abi/abigen/testdata/v2/deeplynestedarray.go.txt, accounts/abi/abigen/testdata/v2/getter.go.txt, accounts/abi/abigen/testdata/v2/identifiercollision.go.txt, accounts/abi/abigen/testdata/v2/inputchecker.go.txt, accounts/abi/abigen/testdata/v2/interactor.go.txt, accounts/abi/abigen/testdata/v2/nameconflict.go.txt, accounts/abi/abigen/testdata/v2/numericmethodname.go.txt, accounts/abi/abigen/testdata/v2/outputchecker.go.txt, accounts/abi/abigen/testdata/v2/overload.go.txt, accounts/abi/abigen/testdata/v2/rangekeyword.go.txt, accounts/abi/abigen/testdata/v2/slicer.go.txt, accounts/abi/abigen/testdata/v2/structs.go.txt, accounts/abi/abigen/testdata/v2/token.go.txt, accounts/abi/abigen/testdata/v2/tuple.go.txt, accounts/abi/abigen/testdata/v2/tupler.go.txt, accounts/abi/abigen/testdata/v2/underscorer.go.txt, accounts/abi/bind/v2/internal/contracts/db/bindings.go, accounts/abi/bind/v2/internal/contracts/events/bindings.go, accounts/abi/bind/v2/internal/contracts/nested_libraries/bindings.go, accounts/abi/bind/v2/internal/contracts/solc_errors/bindings.go, accounts/abi/bind/v2/internal/contracts/uint256arrayreturn/bindings.go
=> accounts/abi: generate TryPack* methods for abigen v2 bindings #31692

console/console.go
=> console: fix inconsequential goroutine leak #20667

cmd/XDC/accountcmd.go, cmd/XDC/dbcmd.go, cmd/XDC/main.go, cmd/ethkey/utils.go, console/bridge.go, console/console.go, console/console_test.go, console/prompt/prompter.go
=> cmd, console: password input fixes #20960

console/console.go
=> console: use default APIs when server doesn't have rpc_modules #26267

XDCxlending/lendingstate/lendingitem_test.go, contracts/blocksigner/blocksigner_test.go, contracts/utils_test.go, contracts/validator/validator_test.go, event/event_test.go, p2p/discover/udp_test.go
The PR removes deprecated uses of math.rand for test files.
Ref: #26710
=> all: remove deprecated uses of math.rand #26710

metrics/exp/exp.go, metrics/gauge_info.go, metrics/log.go, metrics/metrics.go, metrics/resetting_timer.go, metrics/syslog.go
=> metrics: fix some typos in comments and names #31023

Dockerfile, Dockerfile.bootnode, Dockerfile.node, cicd/Dockerfile
ref: https://github.com/XinFinOrg/XDPoSChain/pull/1476
After upgrade golang to v1.25.1, we must set `GODEBUG="randseednop=0"`
Without the ENV the mainnet node runs into sync stuck error.
This PR adds the ENV by default to the runtime image for docker deployment
=> fix: add default env to runtime image

accounts/keystore/keystore.go
using runtimme.AddCleanup #32610
=> accounts/keystore: use runtime.AddCleanup #32610

consensus/tests/engine_v1_tests/helper.go, consensus/tests/engine_v2_tests/helper.go, core/chain_makers.go, core/state_processor.go, eth/tracers/api.go, miner/worker.go
The `err` should be the last return value in function signature.
=> all: move err to the last position of return values

.pre-commit-config.yaml, docs/README.md, docs/develop.md
This PR implements git client hook and closes #1578.
=> docs: implement git client hook, close #1578

eth/gasestimator/gasestimator.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go
=> eth/gasestimator, internal/ethapi: move gas estimator out of rpc #28600

accounts/keystore/keystore.go
accounts/keystore: use ticker to avoid timer allocations #32732
=> accounts/keystore: use ticker to avoid timer allocations #32732

eth/api.go, internal/ethapi/api.go
=> internal/ethapi: use correct signer when serving old blocks #23683

internal/ethapi/api.go
=> internal/ethapi: fix encoding of uncle headers and pending blocks #20460

consensus/XDPoS/engines/engine_v2/verifyHeader.go
fix audit issue XFN-16: Missing Minimum Timestamp Check For The First v2 Block After The Switch
=> engine_v2: check minimum timestamp for the first v2 block, close XFN-16
